feat: Incorporate inputMedia into mainComposer
devhatt/octopost pull request #185
Opened 2023-11-01 19:17 UTC by JpBurgarelli

Feat #180 

- **Description**
- Incorporate inputMedia into mainComposer 

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

https://github.com/Alecell/octopost/assets/30197026/35675c7b-13a6-459a-a792-04d826678de4

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Tests weren`t created
</details>

2023-11-01 20:46 UTC, kingjotaro commented
tem que assinar a pr

2023-11-01 20:49 UTC, kingjotaro approved these changes

2023-11-01 20:52 UTC, aalmeida00 approved these changes

2023-11-02 14:58 UTC, aalmeida00 submitted a review, later dismissed

2023-11-02 15:00 UTC, Alecell requested changes
Tambem crie um teste no playwright do funcionamento desse componente dentro do main composer

2023-11-02 15:00 UTC, Alecell commented on src/components/MainComposer/MainComposer.tsx
>  import '../../i18n';
Arrumar o import do i18n, ele deve ser por path alias

2023-11-17 23:14 UTC, aalmeida00 requested changes

2023-11-17 23:14 UTC, aalmeida00 commented on src/components/ComposerEditor/ComposerEditor.tsx
> +import CustomTextArea from '../TextArea/TextArea'; // Importe o componente CustomTextArea aqui
Vale sempre olhar o código que está sendo mexido. Nesse caso esses comentários nao eram necessários, pode remover.

```suggestion
import CharacterLimitMainText from '../CharacterLimitMainText/CharacterLimitMainText'; 
import CustomTextArea from '../TextArea/TextArea'; 
```

2023-11-17 23:14 UTC, aalmeida00 commented on src/components/MainComposer/MainComposer.module.scss
> +.contentBotBotInputMedia {
Quer explicar o nome dessa classe? Nao ficou boa nao. BotBotInputMedia? Esquisito né, vale mudar.

```suggestion
.contentBotBotInputMedia {
```

2023-11-17 23:14 UTC, aalmeida00 commented on src/components/MediaInputs/MediaInput.spec.ct.tsx
> +import MediaInputs from './MediaInput'; // Forna de importar diferente
Pode evitar comentário desnecessário

```suggestion
import MediaInputs from './MediaInput';
```

2023-11-21 21:09 UTC, aalmeida00 submitted a review, later dismissed

2023-11-21 21:22 UTC, kingjotaro submitted a review, later dismissed

2023-11-22 00:44 UTC, Alecell requested changes

2023-11-22 00:44 UTC, Alecell commented on src/components/CharacterLimitMainText/components/CharacterLimit.module.scss
>    fill: global.$primaryWhite !important;
Sem important

2023-11-22 00:44 UTC, Alecell commented on src/components/ComposerEditor/ComposerEditor.module.scss
> +@use '../../styles/global.scss';
Não da pra usar path alias aqui?

2023-11-22 00:44 UTC, Alecell commented on src/components/ComposerEditor/ComposerEditor.tsx
> +import CustomTextArea from '../TextArea/TextArea';
Pq ta sem o path alias?

2023-11-22 00:44 UTC, Alecell commented on src/components/MainComposer/MainComposer.module.scss
> +}
Mantem a estrutura do html no css

2023-11-22 00:44 UTC, Alecell commented on src/components/MainComposer/MainComposer.tsx
> +import MediaInputs from '../MediaInputs/MediaInput';
Path alias

2023-11-22 21:12 UTC, aalmeida00 submitted a review, later dismissed

2023-11-23 14:13 UTC, aalmeida00 commented
Tem que arrumar os conflitos

2023-12-04 16:21 UTC, aalmeida00 approved these changes

2023-12-06 02:23 UTC, Alecell approved these changes
POOOG

2023-12-06 02:23 UTC, merged