Issue 179
devhatt/octopost pull request #232
Opened 2023-11-27 18:47 UTC by PiluVitu

Closes #179 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Sentry integrado com o projeto
Erros são capturados e aparecem no dashboard do Sentry  
</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- Adicionei o sentry no app.tsx
- Englobei as rotas com o sentry 
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/hatcoders/octopost/assets/69992923/2f1f0353-554d-4681-90f2-afb9c3743b33)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-11-27 19:19 UTC, hxsggsz approved these changes

2023-11-27 21:29 UTC, aalmeida00 requested changes

2023-11-27 21:29 UTC, aalmeida00 commented on src/App.tsx
> +  dsn: 'https://bd204ec3d8157e7eb3c2fd1c1d010610@o4506298178404352.ingest.sentry.io/4506298185154560',
Isso daqui parece ser alguma env. Mover para dotenv

2023-11-27 23:02 UTC, PiluVitu commented on src/App.tsx
> +  dsn: 'https://bd204ec3d8157e7eb3c2fd1c1d010610@o4506298178404352.ingest.sentry.io/4506298185154560',
É uma env de dev, vou mover pra um `.env.development`

2023-11-28 23:53 UTC, Alecell approved these changes
Só me confirma uma coisa, vc testou se o Sentry ta logando?

Tipo, ta tendo logs quando a gente toma erro no front?

2023-11-28 23:53 UTC, Alecell commented on package.json
> +    "node": "18.18.2",
brabo

2023-11-29 00:21 UTC, aalmeida00 requested changes

2023-11-29 00:21 UTC, aalmeida00 commented on .env.example
> +SENTRY_KEY = key do sentry aki
eof + ajustar.
```suggestion
SENTRY_KEY=sentry_key

```

2023-11-29 20:00 UTC, aalmeida00 approved these changes

2023-11-29 20:01 UTC, merged