Change yarn to pnpm and remove deprecated dependencies
devhatt/octopost pull request #245
Opened 2023-12-04 17:53 UTC by Sherlockzen

Closes #238 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Foi trocado o yarn pelo pnpm, também foi excluido algumas dependencias depreciadas.
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>

- Projeto Rodando com pnpm

![image](https://github.com/devhatt/octopost/assets/90076846/220da3da-d222-447a-b1f0-da9e56d2bb34)

</details>

2023-12-04 17:55 UTC, PiluVitu approved these changes

2023-12-04 18:02 UTC, hxsggsz approved these changes

2023-12-04 20:11 UTC, GabrielTrindadeC approved these changes

2023-12-04 20:11 UTC, GabrielTrindadeC requested changes
trocar o yarn das actions pra pnpm

2023-12-04 20:45 UTC, aalmeida00 requested changes
Tem que mudar no dependabot também

2023-12-05 16:11 UTC, alvarogfn commented
https://github.com/actions/setup-node/issues/304

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

https://github.com/pnpm/action-setup

https://pnpm.io/npmrc#use-node-version

2023-12-05 16:23 UTC, alvarogfn reviewed
Você pode aproveitar as funcionalidades do pnpm para deixar mais fácil do pessoal utilizar o projeto. 

No .npmrc, você pode adicionar o seguinte conteúdo:

```
use-node-version=18.18.2
node-version=12.22.0
engine-strict=true
```

O `use-node-version` vai fazer o papel do nvm, e setar a versão do node automaticamente. 
O `node-version` vai bloquear dependencias que não suportam a versão 18 do node.
O `engine-strict` vai bloquear o usuário de utilizar outras versões do node.

Se quiser saber mais, dá uma olhada na documentação do pnpm: https://pnpm.io/npmrc

2023-12-05 16:41 UTC, alvarogfn commented on README.md
>  Para começar com o OctoPost, siga estes passos:
Aqui seria bom adicionar um TO-DOzinho de quais programas você precisa para iniciar o projeto. Por exemplo

\### Instale o Git
Link para o site do git
\### Instale o pnpm
Link para o site do pnpm
(Aqui é importante mencionar que a instalação do pnpm pelo `standalone script` é mais rápido que instalar pelo npm install -g pnpm)

2023-12-05 16:41 UTC, alvarogfn commented on README.md
> -3. Iniciar o aplicativo: **`yarn start`**
Vc pode utilizar o 

\```bash
pnpm # instala todas as dependências do projeto
\```

Para deixar bonitinho com o syntax highlight

2023-12-05 16:41 UTC, alvarogfn commented on .github/workflows/main.yml
>        - name: Install and build
Separa os scripts de install & build em steps diferentes, você vai conseguir mensurar o tempo de cada uma melhor para alguma melhoria futura.

2023-12-05 16:41 UTC, alvarogfn commented on .github/workflows/main.yml
>        - name: Run Vitest tests
Seria bom que os testes rodassem antes do build. Pensa que não faz sentido você buildar um projeto que os testes não estão funcionando. Dessa forma, vamos economizar tempo de build nos casos que os testes não estão funcionando.

2023-12-05 17:23 UTC, Sherlockzen commented
> trocar o yarn das actions pra pnpm

Feito!

2023-12-05 17:24 UTC, Sherlockzen commented
> Tem que mudar no dependabot também

Ajustado!

2023-12-05 17:26 UTC, Sherlockzen commented on .github/workflows/main.yml
>        - name: Run Vitest tests
![image](https://github.com/devhatt/octopost/assets/90076846/fd3e627b-2f04-405d-b9c7-d7c30d464195)
Opa, realizado!

2023-12-05 17:28 UTC, Sherlockzen commented on .github/workflows/main.yml
>        - name: Install and build
Separado, cada um com seu step!

2023-12-05 18:57 UTC, GabrielTrindadeC approved these changes

2023-12-06 01:58 UTC, Alecell approved these changes
EU SÓ QUERO SABER QUEM AUTORIZOU UMA TASK HEREGE DESSAS PASSAR U.U

2023-12-06 12:03 UTC, aalmeida00 approved these changes

2023-12-06 14:04 UTC, PiluVitu approved these changes

2023-12-06 14:23 UTC, merged