Add BreakPoint
devhatt/octopost pull request #250
Opened 2023-12-05 22:20 UTC by JpBurgarelli

Closes #172 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Breakpoints/media queries Foram Criado. Abaixo O conteúdo MainContent foi usado como um exemplo.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

https://github.com/devhatt/octopost/assets/30197026/d1df604c-282d-4811-a33e-af733617d256

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

Uma nova task foi criado para resolver o problema com o grid que, conforme a visualização da viewport diminui, o "Header" permanece fixo e não diminui conforme esperado.

Referência utilizada: https://dev.to/rembertdesigns/how-to-write-media-queries-with-sass-mixins-32e

</details>

2023-12-05 23:56 UTC, aalmeida00 requested changes

2023-12-05 23:56 UTC, aalmeida00 commented on src/components/MainComposer/MainComposer.module.scss
> +  // Estilos padrão que se aplicam a todas as telas
```suggestion
```

2023-12-05 23:56 UTC, aalmeida00 commented on src/components/MainComposer/MainComposer.module.scss
> +  }
```suggestion
```

2023-12-05 23:56 UTC, aalmeida00 commented on src/components/MainComposer/MainComposer.module.scss
> +    background-color: global.$secondaryPurple;
```suggestion
```

2023-12-06 01:54 UTC, Alecell submitted a review, later dismissed

2023-12-06 01:54 UTC, Alecell commented on src/styles/global.scss
> +}
Alguns ajustes

Colocar os breaking points em variáveis pra reusar quando/caso seja necessário
```scss
$tabletSmall: 600rem;
```
----
Ajustar nomeclatura, a pesar de que podemos usar nomes acredito que é melhor algo como 
```scss
@mixin from600 {
    @media (max-width: 599px) {
      @content;
    }
}
```

Assim, pelo nome da função já sabemos qual resolução esse breaking point afeta

----

Usar media **screen** e não apenas media. `@media screen` afeta apenas a tela, `@media` sozinho afeta qualquer coisa, isso não é muito desejado

---- 

Não usar `px` para media queries! Apenas `rem` e nada mais!

----

Sugiro usarmos essas resoluções

Vale dizer, aqui eu referencio a resolução como `px`, mas na media query precisa ser `rem`.

320px
360px
350px
400px
480px
600px
720px
840px
960px
1024px
1280px
1440px
1600px
1920px

Meu artigo pode ajudar nisso: https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/

2023-12-06 13:35 UTC, JpBurgarelli commented on src/components/MainComposer/MainComposer.module.scss
> +  }
O uso do MainComposer vou meramente ilustrativo, ja tirei as breakpoints dele.

2023-12-06 13:36 UTC, JpBurgarelli commented on src/components/MainComposer/MainComposer.module.scss
> +    background-color: global.$secondaryPurple;
O uso do MainComposer vou meramente ilustrativo, ja tirei as breakpoints dele.

2023-12-06 16:01 UTC, Alecell requested changes

2023-12-06 16:01 UTC, Alecell commented on src/styles/global.scss
Isso aqui nao pode ser no global, tem que ser no breakpoints.scss

2023-12-09 14:31 UTC, alvarogfn commented on .github/dependabot.yml
> -        update-types: ['minor', 'patch']
EOF

2023-12-11 14:24 UTC, aalmeida00 submitted a review, later dismissed

2023-12-11 15:41 UTC, Alecell requested changes

2023-12-11 15:41 UTC, Alecell commented on .github/dependabot.yml
EOF

2023-12-11 15:41 UTC, Alecell commented on src/styles/breakpoints.scss
> +@mixin from599 {
Ou a gente usa 599 ou a gente usa 480, no sentido de numeros inteiros. Preciso que vc **teste** os breaking points pra saber se ele ta tringando na resolução esperada

No caso, ou o 480 seria 479 ou o 599 seria 600, não faz sentido um ser quebrado e o outro não

2023-12-12 06:05 UTC, Luiginicoletti reviewed
Fiz alguns comentários jp, bom pr. abracao.

2023-12-12 06:05 UTC, Luiginicoletti commented on src/components/MainComposer/MainComposer.module.scss
> +        float: left;
Acho que quando usar float-left nao precisa usar inlineblock, alias, float é uma propriedade um pouco desatualizada. tenta usar flexbox ou grid.

2023-12-12 06:05 UTC, Luiginicoletti commented on src/components/MainComposer/MainComposer.module.scss
> +        float: left;
https://dev.to/ethanmgustafson/css-float-flexbox-14fghttps://dev.to/ethanmgustafson/css-float-flexbox-14fg

2023-12-12 15:52 UTC, aalmeida00 approved these changes

2023-12-12 18:51 UTC, aalmeida00 approved these changes

2023-12-12 18:55 UTC, Alecell approved these changes

2023-12-12 18:55 UTC, merged