Tabber/#34
devhatt/octopost pull request #252
Opened 2023-12-06 13:18 UTC by leandrokzu

Closes #34 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Created Tabber component
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/61525671/3e5f007d-c43f-4e99-ba29-36587b98394c)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

Sorry, but I got confused and built the Inside Tabber, which renders Post Modes. That's another separate task.
</details>

2023-12-06 14:10 UTC, Alecell requested changes
Alguns ajustes

2023-12-06 14:10 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +      ))}
Sem map dentro de componente, coloca numa função

2023-12-06 14:10 UTC, Alecell commented on src/components/Tabber/Tabs/Tabs.module.scss
> +    line-height: 20px;
Usar o valor sem unidade

2023-12-06 14:10 UTC, Alecell commented on src/components/Tabber/Tabs/Tabs.module.scss
> +    font-size: 14px;
Usar `rem`

2023-12-06 14:10 UTC, Alecell commented on src/components/Tabber/Tabs/Tabs.module.scss
> +    letter-spacing: 0.1px;
Usar `rem`

2023-12-06 14:10 UTC, Alecell commented on src/components/Tabber/Tabs/Tabs.tsx
> +      ))}
Mover o map pra uma função

2023-12-06 15:58 UTC, Alecell requested changes

2023-12-06 15:58 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +}
Vamos falar sobre isso, acho que da pra melhorar um cadin

2023-12-06 15:58 UTC, Alecell commented on src/components/Tabber/Tabs/Tabs.tsx
> +  return <div className={scss.tabsContainer}>{RenderTabs()}</div>;
Mesma coisa, vamos falar sobre isso

2023-12-11 17:21 UTC, aalmeida00 submitted a review, later dismissed

2023-12-11 17:27 UTC, Alecell requested changes

2023-12-11 17:27 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +    : currentTab.postModes[0];
Role que falamos

2023-12-11 17:27 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +  );
Confio em vc

2023-12-12 20:38 UTC, Alecell approved these changes
POG

2023-12-12 20:38 UTC, merged