create FeedbackError component
devhatt/octopost pull request #265
Opened 2023-12-07 16:57 UTC by hxsggsz

Closes #176 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

create FeedbackError component and linked the error message to a zustand store
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
 - fixed build error on button component
 - add icon component props to ladle
 - create errorMessage store
 - create FeedbackError component
 - fixed blank area when first comment checkbox is marked
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

https://github.com/devhatt/octopost/assets/103784814/77dcabdb-1045-452d-92e1-6c0c02c54649

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>
i couldn't create a component test when there is a error message because there is no button on layout that create a error message but I'm testing this case on zustand's store.
</details>

2023-12-08 13:01 UTC, aalmeida00 requested changes

2023-12-08 13:01 UTC, aalmeida00 commented on src/styles/global.scss
> +}
Isso daqui já vai vir em outro PR, dá pra tirar né?

2023-12-08 13:01 UTC, aalmeida00 commented on src/components/Button/icons/LocationIcon.svg
Tem que olhar se a gente vai fazer assim com o Icone, vale perguntar pro Ale.

2023-12-08 13:02 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.module.scss
> +      background-image: url('./assets/IconErrorRed.svg');
Usar o componente de icone do @Luiginicoletti

2023-12-08 13:02 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.module.scss
> +    }
media query sempre usadas no final do arquivo css, **nunca** junto com as propriedades

2023-12-08 13:06 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.tsx
> +  const errorMessage = useFeedbackError((state) => state.errorMessage);
Essa store poderia se chamar useError, não pode ser uma store tão específica assim pra um componente

2023-12-08 13:07 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.tsx
> +      <i className={scss.icon} />
Esse cara é pra ser o componente do `icon`

2023-12-11 14:28 UTC, Alecell reviewed
Não entendi, vc colocou o icone no icomoon?

2023-12-11 15:09 UTC, hxsggsz commented on src/styles/global.scss
> +}
foi necessario deixar no meu projeto porque a CI não tava passando na hora do build

![image](https://github.com/devhatt/octopost/assets/103784814/55dd1096-0b64-4418-8a22-3bb4c9265c28)

2023-12-11 15:50 UTC, Alecell requested changes

2023-12-11 15:50 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.stories.tsx
> +import FeedbackError from './FeedbackError';
Da um espaço aqui em baixo

2023-12-11 17:20 UTC, aalmeida00 approved these changes

2023-12-11 17:20 UTC, Alecell approved these changes

2023-12-11 17:20 UTC, merged