chore: fix auto-milestone and unassign issue after 7 days
devhatt/octopost pull request #266
Opened 2023-12-10 01:28 UTC by k1nha

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-12-10 21:10 UTC, aalmeida00 commented on .github/workflows/unassignIssue.yml
> +    name: Unassign issues labeled "Wartet auf Contributor" after 7 days of inactivity.
Qual o negocio dessa label aqui?
```suggestion
    name: Unassign issues labeled "Wartet auf Contributor" after 7 days of inactivity.
```

2023-12-10 21:10 UTC, aalmeida00 submitted a review, later dismissed

2023-12-11 13:21 UTC, k1nha commented on .github/workflows/unassignIssue.yml
> +    name: Unassign issues labeled "Wartet auf Contributor" after 7 days of inactivity.
nada, esse name é exemplo da action na actions marketplace
achei que tivesse mudado, vou arrumar

2023-12-11 14:25 UTC, Alecell submitted a review, later dismissed

2023-12-11 18:24 UTC, aalmeida00 requested changes

2023-12-11 18:25 UTC, aalmeida00 approved these changes

2023-12-11 18:26 UTC, merged