Issue 249/grid fix
devhatt/octopost pull request #268
Opened 2023-12-12 01:01 UTC by Felipeness

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-12-12 01:07 UTC, alvarogfn requested changes

2023-12-12 05:49 UTC, Luiginicoletti commented on src/components/MediaInputs/MediaInput.module.scss
> +  justify-content: flex-start;
Acho que não existe a propriedade "start" creio que seja flex-start mesmo

2023-12-12 12:46 UTC, Felipeness commented on src/components/MediaInputs/MediaInput.module.scss
> +  justify-content: flex-start;
Tem sim nico, flex é só para display flex , botei display flex por 2 motivos , na primeira vez o start sozinho não tava pegando, e a segundo é a força do hábito kkk

2023-12-13 12:55 UTC, aalmeida00 approved these changes

2023-12-13 12:57 UTC, merged