Issue 237
devhatt/octopost pull request #280
Opened 2023-12-15 19:11 UTC by alvarogfn

Closes #237 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-09 22:04 UTC, aalmeida00 commented
@alvarogfn ajustar conflitos e atualizar a branch

2024-01-11 03:04 UTC, aalmeida00 commented
@alvarogfn arruma os conflitos antes de abrir o PR.

2024-01-18 01:01 UTC, Alecell requested changes

2024-01-18 01:21 UTC, Alecell requested changes
Testa mais uam vez

2024-01-18 17:22 UTC, Alecell submitted a review, later dismissed

2024-01-18 20:10 UTC, Felipeness approved these changes

2024-01-18 20:11 UTC, Sherlockzen approved these changes

2024-01-18 20:39 UTC, aalmeida00 approved these changes

2024-01-18 21:47 UTC, merged