refactor: create function to get package.json content
devhatt/octopost pull request #290
Opened 2023-12-19 18:09 UTC by hxsggsz

Closes #275 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

create function to get metadata inside all modules folder
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

- refactor `resolveModulePath` function
- create `readPackage` function
- create `resolveModulesMetadata` function

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

https://github.com/devhatt/octopost/assets/103784814/89278051-5bbe-48b3-a4a2-a186b21ba62e

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

2023-12-19 18:46 UTC, aalmeida00 requested changes

2023-12-19 18:46 UTC, aalmeida00 commented on electron/main.ts
> +    // necessário para o typescript entender que o packagePath nunca será undefined
![image](https://github.com/devhatt/octopost/assets/61947632/bbd1489a-58e7-4bfb-92cb-b7580d5d466f)

2023-12-20 00:06 UTC, alvarogfn requested changes

2023-12-20 00:06 UTC, alvarogfn commented on electron/utils/readPackage/readPackage.types.ts
> +  repository?: IPluginRepository;
Vai ficar mais fácil manipular o objeto se ele só tiver um nível, não imagino esse IPluginRepository sendo utilizado separado 

Aproveitando, para não ficar muito confuso se isso é o link do repositório no github ou o link do código no path, você pode colocar

```tsx
repositoryURL (ou repository_url): string;
path: string;
```

2023-12-20 01:34 UTC, alvarogfn commented on electron/utils/resolveModulesMetadata.ts
> + * @param {strin} pluginsPath - path to folder where all plugins are installed
string?

2023-12-20 01:34 UTC, alvarogfn commented on electron/utils/resolveModulesMetadata.ts
> +  pluginsPath: string
Não acha que o nome pluginsDir ou PluginsFolder seria mais semântico?

2023-12-20 19:39 UTC, alvarogfn approved these changes

2023-12-21 12:11 UTC, aalmeida00 approved these changes

2023-12-21 14:39 UTC, merged