Issue 298
devhatt/octopost pull request #299
Opened 2023-12-26 22:15 UTC by alvarogfn

```
 TODO: ja ja descrevo
```

2024-01-02 20:34 UTC, Alecell requested changes

2024-01-02 20:34 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.data.ts
> +    y: -100,
Desgósto, fica mais bacanudo em cima as propriedades

2024-01-02 20:34 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.tsx
> +  return <AnimatePresence>{!!errorMessage && renderError()}</AnimatePresence>;
Mesma coisa, fico me perguntando porque ele faz isso, e talvez seja legal usar `Boolean()`

2024-01-02 20:34 UTC, Alecell commented on src/components/Icon/Icon.tsx
> +  // eslint-disable-next-line unicorn/explicit-length-check
Porque? Oque esta acontecendo pra precisar desse comentario?

2024-01-02 20:34 UTC, Alecell commented on src/components/InputMedia/InputMedia.stories.tsx
> +  onChange: (media) => { alert(`image selected ${media[0].file.name}`); },
Acho isso meio mais ou menos

2024-01-02 20:34 UTC, Alecell commented on src/components/InputMedia/InputMedia.tsx
> +    // eslint-disable-next-line jsx-a11y/media-has-caption
WHYYYYY??

2024-01-02 20:34 UTC, Alecell commented on src/components/InputMedia/InputMedia.tsx
> +      {!!props.files && renderMedia()}
NOOOOO

2024-01-02 20:34 UTC, Alecell commented on src/components/InputSearch/InputSearch.tsx
> +    // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions
NOOOOOO

2024-01-02 20:34 UTC, Alecell commented on src/components/Modal/Modal.stories.tsx
> +      <Portal isOpen={isOpen} onClickOutside={() => { setIsOpen(false); }}>
Da não, vo morre

2024-01-02 20:34 UTC, Alecell commented on src/components/Modal/Modal.tsx
> +            // eslint-disable-next-line jsx-a11y/click-events-have-key-events,, jsx-a11y/no-static-element-interactions
DOI

2024-01-02 20:34 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +      // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions
NOOOO

2024-01-02 20:34 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +      socialNetwork.currentPostModeId ?? buildPostModeId(socialNetwork);
AQUI FOI GOD

2024-01-02 20:34 UTC, Alecell commented on src/components/Tabber/Tabs/Tabs.tsx
> +    // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions
MNOOOOOOO

2024-01-02 20:34 UTC, Alecell commented on src/components/Testinho/Testinho.tsx
> +/* eslint-disable react/destructuring-assignment */
NOOO

2024-01-02 20:34 UTC, Alecell commented on src/components/TextArea/TextArea.spec.tsx
> +    ) ;
Tem um mini espacinho aqui e porque ele removeu o `as`?

2024-01-02 20:34 UTC, Alecell commented on src/i18n/index.ts
> +/* eslint-disable import/no-named-as-default-member */
NOOOO

2024-01-02 20:34 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
> +        <SocialAccordion accountList={[]} error socialMediaName="facebook" />
Ia ser legal se propriedades standalone (tipo esse error) ficassem sempre no inicio da declaração do componente

2024-01-02 20:34 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +              {!!props.error && renderError()}
AAAAAA

2024-01-02 20:34 UTC, Alecell commented on src/stores/useError/useError.ts
> +  setErrorMessage: (errorMessage) => { set({ errorMessage }); },
BBBBB

2024-01-02 21:41 UTC, alvarogfn commented on src/components/Accordion/Accordion.tsx
> +        {!!props.isOpen && (
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md

2024-01-02 21:41 UTC, alvarogfn commented on src/components/Button/Button.tsx
> +        // eslint-disable-next-line react/button-has-type
Recebe, mas a regra valida de forma estática. Se for uma variável, a regra não funciona

2024-01-02 21:42 UTC, alvarogfn commented on src/components/Button/Button.tsx
> +        // eslint-disable-next-line react/button-has-type
Recebe, mas a regra valida de forma estática. Se for uma variável, a regra não funciona

2024-01-02 21:42 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.types.ts
> +export interface TCheckboxProps {
É bom escolher se vai usar type ou interface para manter a consistência e o padrão entre os componentes.

2024-01-02 22:39 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.types.ts
> +  checked: boolean;
nao tem, tem que escolher entre alfabeticamente, tamanho, ou caos

2024-01-02 22:39 UTC, alvarogfn commented on src/components/ComponentPreview/PreviewContainer.tsx
> +function PreviewContainer(props: IPreviewContainerProps) {
Componentes no topo do arquivo serão por functions, e componentes dentro de componentes por arrow declaration. Mas dá mudar

2024-01-02 22:40 UTC, alvarogfn commented on src/components/FeedbackError/FeedbackError.tsx
> +  return <AnimatePresence>{!!errorMessage && renderError()}</AnimatePresence>;
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md

2024-01-02 22:41 UTC, alvarogfn commented on src/components/Icon/Icon.tsx
> +  // eslint-disable-next-line unicorn/explicit-length-check
É por causa do nome props.size

A biblioteca unicorn pensa que ta comparando tamanho de um array.

Isso é bug

2024-01-02 22:42 UTC, alvarogfn commented on src/components/InputMedia/InputMedia.tsx
> +    // eslint-disable-next-line jsx-a11y/media-has-caption
Esse ai vai ser dificil implementar, é regra de eslint pra sempre por legenda em vídeos.

2024-01-02 22:43 UTC, alvarogfn commented on src/components/InputSearch/InputSearch.tsx
> +    // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions
msm coisa, isso ai vai dar trabalho fazer

2024-01-02 22:47 UTC, alvarogfn commented on src/components/TextArea/TextArea.spec.tsx
> +    ) ;
unnecessary casting ele remove

2024-01-09 22:05 UTC, aalmeida00 commented
Atualziar branch.

2024-01-16 22:39 UTC, aalmeida00 approved these changes
Muito bom! Mas só se atenta ao escopo da tarefa, ela foi crescendo, e o ideal era ser algo menor e mais simples, pequenas entregas tem muito valor.

2024-01-17 14:08 UTC, hxsggsz approved these changes

2024-01-18 01:18 UTC, Alecell approved these changes

2024-01-18 02:32 UTC, merged