Issue 251 - Criação de Modal conforme design
devhatt/octopost pull request #304
Opened 2024-01-04 15:24 UTC by Sherlockzen

Closes #251 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Implementação do design do modal.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>

![modal-eg](https://github.com/devhatt/octopost/assets/90076846/e1eab2cd-a9ce-43da-a08f-0c81df8f3d47)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
O emote de carinha ali representa o botão de close que será com X só que precisamos implementar esse icone no componente **icon**
</details>

2024-01-04 21:18 UTC, aalmeida00 commented on src/components/Modal/Modal.module.scss
> +  background-color: #fff;
fff ou temos uma var pra cor branca?

2024-01-04 21:18 UTC, aalmeida00 commented on src/components/Modal/Modal.module.scss
> +  scrollbar-color: #7a757f;
Essa cor nao tá no DS? Coloca uma var pra ela

2024-01-04 21:18 UTC, aalmeida00 commented on src/components/Modal/Modal.tsx
> +            onClick={(e) => e.stopPropagation()}
```suggestion
            onClick={(event) => event.stopPropagation()}
```

2024-01-05 16:55 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
> +  background-color: #fff;
Resolvido!

2024-01-05 16:55 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
> +  scrollbar-color: #7a757f;
Resolvido!

2024-01-05 16:56 UTC, Sherlockzen commented on src/components/Modal/Modal.tsx
> +            onClick={(e) => e.stopPropagation()}
Resolvido!

2024-01-05 17:12 UTC, Alecell requested changes

2024-01-05 17:12 UTC, Alecell commented on src/components/Modal/Modal.module.scss
Sinto que tem coisa errada no lint do scss, tem muito espaçamento, sinto que tem muito espaçamento que não existe

2024-01-05 17:12 UTC, Alecell commented on src/components/Modal/Modal.module.scss
> +  background-color: #21005d29;
usar rgba

2024-01-05 17:12 UTC, Alecell commented on src/components/Modal/Modal.module.scss
> +}
Defina o container

2024-01-05 17:12 UTC, Alecell commented on src/components/Modal/Modal.module.scss
> +}
Isso inexiste

2024-01-05 20:03 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
Agrupei alguns pontos na mão mesmo, não sei se o stylelint agruparia de forma automática as propriedades.

2024-01-05 20:05 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
> +  background-color: #21005d29;
Vale colocar essa cor lá no `global.scss` pra ser uma variável?

2024-01-05 20:10 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
> +}
Coloquei no modalContent

2024-01-08 01:57 UTC, Alecell commented
@Sherlockzen preciso que crie issue de adição de icone no Icon component dos icones que vc não tinha quando rpecisava

2024-01-08 11:54 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
> +}
Removido.

2024-01-08 13:09 UTC, aalmeida00 submitted a review, later dismissed

2024-01-08 13:09 UTC, aalmeida00 commented on src/components/Modal/Modal.module.scss
> +    background-color: #f0f0f0;
vale colocar essas cores no globals nao? E a rgba também prob

2024-01-08 14:17 UTC, Alecell approved these changes
Por mim ta bala, resolve o callout do andre e gg

2024-01-08 15:21 UTC, Sherlockzen commented on src/components/Modal/Modal.module.scss
> +    background-color: #f0f0f0;
Eu burrei e não vi que tinha essas cores na nossa lista de cores, a segunda é um white que precisa ser o mesmo do background da octo, então é isso

2024-01-08 15:51 UTC, alvarogfn requested changes

2024-01-08 15:51 UTC, alvarogfn commented on src/components/Modal/Modal.types.ts
> +import React, { MouseEventHandler, PropsWithChildren } from 'react';
import { ReactNode, MouseEventHandler, PropsWithChildren } from 'react';

2024-01-08 15:59 UTC, Sherlockzen commented on src/components/Modal/Modal.types.ts
> +import React, { MouseEventHandler, PropsWithChildren } from 'react';
Done

2024-01-08 16:00 UTC, alvarogfn approved these changes

2024-01-08 17:54 UTC, alvarogfn approved these changes

2024-01-08 21:34 UTC, aalmeida00 approved these changes

2024-01-09 22:06 UTC, merged