feat: converte o MainComposer e o ComposerEditor para controlled
devhatt/octopost pull request #324
Opened 2024-01-16 18:24 UTC by pedromiguelmvs

Closes #318 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Este PR converte os componentes `MainComposer` e `ComposerEditor` em controlled componentes para que possam ser alterados em suas respectivas instâncias.

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
O PR foi marcado como draft e ainda não foi finalizado, vou precisar fazer alinhamentos para evitar `property drilling` e estruturar os testes
</details>

2024-01-17 17:22 UTC, Alecell requested changes

2024-01-17 17:22 UTC, Alecell commented on src/components/CharacterLimitMainText/components/CharacterLimit.tsx
Seja la oque isso resolve, não resolve

2024-01-17 17:22 UTC, Alecell commented on src/components/ComposerEditor/ComposeEditor.spec.tsx
Não ta seguindo styleguide de teste

2024-01-17 17:22 UTC, Alecell commented on src/components/ComposerEditor/ComposerEditor.tsx
> +    props?.onTextChange(newText);
Inconsistente com o tipo

2024-01-17 17:22 UTC, Alecell commented on src/components/ComposerEditor/ComposerEditor.types.ts
> +}>;
Inconsistente com o uso

2024-01-17 17:22 UTC, Alecell commented on src/components/MainComposer/MainComposer.spec.ct.tsx
Reescrever com vitest

2024-01-17 17:22 UTC, Alecell commented on src/components/MainComposer/MainComposer.tsx
> +      onChangeOpen={props.onChangeOpen}
on toggle? Talvez

2024-01-17 17:22 UTC, Alecell commented on src/components/MainComposer/MainComposer.types.ts
> +  onChangeOpen?: () => void;
no argumento, receber o estado de aberto ou fechado, talvez um 

````ts
onChangeOpen?: (open: Boolean) => void;
```

2024-01-17 17:22 UTC, Alecell commented on src/pages/home/home.tsx
> +                />
Crime, declara em uma variavel separada e coloca ela aqui, evitar abrir blocos em tags ao maximo

```ts
const wrapper = <MyComponent />

<div component={wrapper}>
```

2024-01-18 16:18 UTC, pedromiguelmvs commented
Atualização daily 18/01 (não pude estar presente) -
Ainda não tive a oportunidade de aplicar as alterações solicitadas, irei pegar na codebase hoje para iniciar as correções

2024-01-18 17:24 UTC, Alecell commented
> Atualização daily 18/01 (não pude estar presente) - Ainda não tive a oportunidade de aplicar as alterações solicitadas, irei pegar na codebase hoje para iniciar as correções

GOD DEMAIS POR AVISAR BRABO

2024-01-24 14:45 UTC, Alecell requested changes

2024-01-24 14:45 UTC, Alecell commented on src/components/ComposerEditor/ComposerEditor.tsx
> +    if(props?.onTextChange) props.onTextChange(newText);
`props.onTextChange && props.onTextChange(newText);`

2024-01-24 14:45 UTC, Alecell commented on src/components/FirstComment/FirstComment.tsx
> +          <ComposerEditor inputText="" />
Pq colocando a prop vazia?

2024-01-24 14:45 UTC, Alecell commented on src/components/InputMedia/InputMedia.spec.tsx
Pq mexeu nos testes do input media?

2024-01-24 14:45 UTC, Alecell commented on src/components/MainComposer/MainComposer.tsx
> +            <div className={scss.mainComposerInputMedia} data-testid="mediaInputs">
Não usar test-id

2024-01-24 14:45 UTC, Alecell commented on src/components/MediaInputs/MediaInput.spec.tsx
> +  // });
Remover

2024-01-24 14:45 UTC, Alecell commented on src/components/MediaInputs/MediaInput.tsx
> +          data-testid="removeFile"
Sem testid

2024-01-24 14:45 UTC, Alecell commented on src/pages/home/home.tsx
> +  );
Não precisa dos parentesis... Ou precisa?

2024-01-25 11:53 UTC, pedromiguelmvs commented on src/components/FirstComment/FirstComment.tsx
> +          <ComposerEditor inputText="" />
inputText é um valor obrigatório no componente `ComposerEditor`, como não tinha um valor pra colocar no FirstComment eu deixei uma string vazia

2024-01-25 11:55 UTC, pedromiguelmvs commented on src/components/InputMedia/InputMedia.spec.tsx
Durante a migração dos testes de `playwright` para `vitest` eu notei que alguns testes validavam a funcionalidade de upload, mas o componente responsável pelo upload é o `InputMedia`, então fazia mais sentido deixar esses testes lá. O que aconteceu foi apenas uma adição aos testes que já existiam

2024-01-29 15:49 UTC, pedromiguelmvs commented
**Atualização daily (29/01)**
Boa tarde!
Por motivos pessoais vou precisar estar me afastando um pouco do projeto! :/
Infelizmente não poderei concluir a task. A branch está disponível no meu fork do octopost e eu me coloco à disposição para tirar dúvidas de quem pegar a tarefa no futuro

2024-01-29 17:14 UTC, Alecell commented
> **Atualização daily (29/01)** Boa tarde! Por motivos pessoais vou precisar estar me afastando um pouco do projeto! :/ Infelizmente não poderei concluir a task. A branch está disponível no meu fork do octopost e eu me coloco à disposição para tirar dúvidas de quem pegar a tarefa no futuro

F

2024-01-30 13:27 UTC, alvarogfn commented
reprovado @PiluVitu

2024-02-03 16:31 UTC, aalmeida00 approved these changes

2024-02-08 11:29 UTC, Luiginicoletti commented on src/components/FirstComment/FirstComment.tsx
> +          <ComposerEditor inputText="" />
Não seria interessante então deixar opcional com "?"

2024-02-21 00:56 UTC, aalmeida00 approved these changes

2024-02-21 13:28 UTC, PiluVitu commented
Gostaria de saber se o ponto atual do meu código já finalizaria a minha task ou falta algo @Alecell / @aalmeida00 

Atualmente movi a lógica que se encontrava dentro do arquivo `TextArea` para dentro do `ComposerEditor`, falta renomear o `MainComposer`. 

Queria saber se é necessário criar um custom hook para abstrair a lógica dentro desse componente, irei renomear o arquivo e farei alguns ajustes no html do componente e remover divs sem sentido

2024-02-25 19:59 UTC, PiluVitu commented on src/components/MediaInputs/MediaInput.tsx
> +          data-testid="removeFile"
Removido, pois ao meu ver não fazia sentido nem ter tocado nesse arquivo

2024-02-25 23:31 UTC, aalmeida00 submitted a review, later dismissed
lgtm, só alguns pontos que podem ser olhados com mais carinho no futuro.

2024-02-25 23:31 UTC, aalmeida00 commented on src/components/ComposerEditor/ComposeEditor.spec.tsx
> +    it('should mount a textbox', () => {
Should é redundante e repetitivo, pode remover.

```suggestion
    it('mount a textbox', () => {
```

2024-02-25 23:31 UTC, aalmeida00 commented on src/components/InputMedia/InputMedia.spec.tsx
> +  nanoid: vi.fn(() => 'sua-string-especifica-aqui'),
quando a gente mocka o retorno de algo, o ideal é que esse retorno seja algo mais fidedigno com o retorno real, pode ajustar pra um retorno do nanoid que seja mais parecido com o que ele realmente retorna hoje? E trocar os assertions nos testes pra validar essa ID.

Sei que isso ja existia assim, mas vale arrumar

2024-02-25 23:31 UTC, aalmeida00 commented on src/components/InputMedia/InputMedia.spec.tsx
> +      { file: file2, id: 'sua-string-especifica-aqui' },
Sao dois arquivos diferentes, eles vao ter o mesmo id, está correto isso?

2024-02-26 13:16 UTC, PiluVitu commented on src/components/InputMedia/InputMedia.spec.tsx
> +      { file: file2, id: 'sua-string-especifica-aqui' },
O iD ser répetido é apenas uma refrência ao nano id da aplicação, não temos(Eu acho) como saber esse retorno em especifico no teste, mas sabemos que a lib não gera id repitidos

2024-02-26 13:18 UTC, PiluVitu commented on src/components/InputMedia/InputMedia.spec.tsx
> +      { file: file2, id: 'sua-string-especifica-aqui' },
O iD ser répetido é apenas uma refrência ao nano id da aplicação, não temos(Eu acho) como saber esse retorno em especifico no teste, mas sabemos que a lib não gera id repitidos

2024-02-26 14:28 UTC, aalmeida00 approved these changes

2024-02-26 14:41 UTC, alvarogfn requested changes

2024-02-26 14:41 UTC, alvarogfn commented on src/components/CharacterLimitMainText/CharacterLimitMainText.tsx
Não é necessário manter esse "MainText" no CharacterLimit. Ele é um componente genérico de contador de caracteres, não especificamente para o "MainText".

Inclusive recomendaria usar num nome mais comum, como CharacterCounter, InputCounter ou InputCharacterCounter.

2024-02-26 14:41 UTC, alvarogfn commented on src/components/ComposerEditor/ComposerEditor.tsx
>    const module = [
Por qual motivo esse módulo aqui está chumbado no componente? Acredito que ele deveria vir via props e ser customizável. E se eu quiser adicionar mais um módulo dinamicamente?

2024-02-26 14:41 UTC, alvarogfn commented on src/components/ComposerEditor/ComposerEditor.types.ts
> +  onTextChange?: TInputChange;
Eu recomendaria seguir a interface do HTML ao typar os event listeners e values. Isso facilita para que desenvolvedores de fora do projeto entendam o próposito de cada uma das props. Por exemplo:

No HTML, o inputText é especificado como value, o onTextChange só como onChange ou onInputChange.

Isso também facilitaria a integração com bibliotecas como o react-hook-form, que usam os valores default do HTML como nome para suas props.

```tsx
// good: eu já sei que o value tem o mesmo significado semântico do value no HTML.
const TextArea = ({value, onChange}) => {

  return <textarea value={value} onChange={onChange} />
}


// bad: eu preciso olhar o código do componente para saber pq você renomeou a prop, pois eu não tenho certeza se o inputText é mesmo o value ou é outra coisa
const TextArea = ({inputText, onTextChange}) => {

  return <textarea value={inputText} onChange={onTextChange} />
}
```

2024-02-26 14:41 UTC, alvarogfn commented on src/components/ContentEditor/ContentEditor.module.scss
>  .textInput textarea {
Não estilize tags diretamente no CSS. Os estilos devem ser agnósticos ao HTML escrito. Se algum dia algum dev, quiser que isso seja um input ou content editor, isso não deveria quebrar o seu estilo.

Também evite especificar tags encadeadas. Isso é ruim para performance do website como um todo, pois o navegador lê as tags da direita para esquerda, então ele busca TODOS os textareas do APP para então depois filtrar quais estão dentro do .textInput 

Tente manter o css o mais plano possível, sem muito encadeamento.

você pode ler mais sobre escalabilidade de css aqui: 
https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2024-02-27 12:24 UTC, PiluVitu commented on src/components/CharacterLimitMainText/CharacterLimitMainText.tsx
Concordo ctg, mas não vou tocar nesse componente agora, tem uma task especifica para refatorar ele e creio que isso pode ser feito lá

2024-02-27 12:28 UTC, PiluVitu commented on src/components/ComposerEditor/ComposerEditor.tsx
>    const module = [
Eu realmente não sei, vou retirar esse icone que não bate com o que está no figma e jogar o resto para props

2024-02-27 12:36 UTC, Alecell reviewed
Me parece OK, só gostaria de olhar o PR a estrutura com vc pra dar como aprovado

2024-02-27 12:58 UTC, PiluVitu commented on src/components/ComposerEditor/ComposerEditor.tsx
>    const module = [
Tentei retirar o mock, mas ele está diretamente ligado aos teste e usabilidade do characterLimit, ta fugindo mto da minha task

2024-02-27 14:02 UTC, alvarogfn approved these changes
Eu confio

2024-02-27 14:04 UTC, hxsggsz approved these changes

2024-02-27 14:10 UTC, merged