feat: a custom hook to listen to key presses
devhatt/octopost pull request #391
Opened 2024-02-05 23:06 UTC by leandrokzu

Closes #346 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criado um custom hook, useKeyPress, que executa uma função quando a tecla escolhida é pressionada
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
- [ ] Tests created
</details>

2024-02-05 23:10 UTC, leandrokzu commented
Eu tava tentando fazer os testes, mas pelo que eu pesquisei parece que como é um custom hook tem que instalar uma biblioteca nova a:  

@testing-library/react-hooks

É isso mesmo? Nesse caso posso instalar?

2024-02-06 22:07 UTC, alvarogfn reviewed
.

2024-02-06 22:08 UTC, alvarogfn requested changes
Não precisa ser um arquivo tsx, precisa?

2024-02-08 10:58 UTC, Alecell requested changes
Colocar na pasta hooks, é interessante criar uns testes pra esse evento. 

Tambem to curioso, como usa esse hook?

2024-02-08 11:30 UTC, Luiginicoletti commented
Parece interessante.

2024-02-09 13:29 UTC, alvarogfn submitted a review, later dismissed

2024-02-09 13:33 UTC, aalmeida00 requested changes

2024-02-09 13:33 UTC, aalmeida00 commented on src/hooks/useKeyPress/useKeyPress.spec.ts
> +  test('should not call action function when a different key is pressed', () => {
Evite a repetição de should e usamos it ao invés de test()

```suggestion
  it('call action function when target key is pressed', () => {
    renderHook(() => useKeyPress(targetKey, action));

    act(() => {
      const event = new KeyboardEvent('keydown', { key: targetKey });
      window.dispatchEvent(event);
    });

    expect(action).toHaveBeenCalled();
  });

  it('not call action function when a different key is pressed', () => {
```

2024-02-09 16:13 UTC, aalmeida00 approved these changes

2024-02-20 22:00 UTC, merged