Testing strategies
devhatt/octopost pull request #395
Opened 2024-02-08 03:09 UTC by Alecell

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  There was some issues when trying to run component testing, some vitest files was running longside them cause of the pattern patching of these testing files.

- **Cause**
  There wasnt a exclude patterns added on vitest config, causing the component testing ones to run with the vitest files

- **Solution**
Add the pattern for component testing as excluded files on vitest config
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
- update `npm start` command
- update `electron:dev` command
- add vite config file specific for electron
- add vite config file specific for web
- add tests examples for each test layer
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/13935760/32054d75-fe64-4de1-a654-f5dd79945d52)

![image](https://github.com/devhatt/octopost/assets/13935760/a3eded92-6e7a-4cf3-9c7e-ce6689a38c2b)

![image](https://github.com/devhatt/octopost/assets/13935760/3aee5c48-fdbd-4ec9-96f7-3f00512a8020)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Build working correctly
- [x] Tests created
</details>

2024-02-08 16:11 UTC, alvarogfn requested changes
Gostei do seu PR, corrige um bug bastante chato do nosso projeto.

Mas será que você não poderia dar uma aumentada no coverage pra 90%? :P

2024-02-08 21:14 UTC, aalmeida00 approved these changes

2024-02-09 02:55 UTC, alvarogfn approved these changes

2024-02-09 02:55 UTC, alvarogfn commented on src/utils/test.ts
> +  console.log('aiusydgbhaisudhasui');
Jdoajdiabdwobdiwbdkwnxne

2024-02-25 19:05 UTC, merged