feature/issue-320
devhatt/octopost pull request #412
Opened 2024-02-27 16:08 UTC by alvarogfn

Closes #320,

Adicionei typecheck no hook de pre-commit e antes do comando de build

2024-02-27 20:42 UTC, aalmeida00 approved these changes
A descrição do PR está ruim, se voce iria apenas adicionar typecheck no build e modificou 25 arquivos, e eles não estão descritos, algo está errado. É bom melhorar esse ponto.

2024-03-02 04:48 UTC, aalmeida00 approved these changes

2024-03-15 15:36 UTC, Alecell requested changes
Fui super deboas nessa review, só coloca um TODO no comentario e gg

2024-03-15 15:36 UTC, Alecell commented on src/components/InputSearch/InputSearch.spec.tsx
> +// Desejo trocar as desestruturações do componente render para usar diretamente no screen em todos esses métodos
Esse comentário pelo menos faz como um `TODO:` se nao vou desmaiar

2024-03-15 16:43 UTC, Alecell approved these changes

2024-03-15 16:44 UTC, merged