refactor: checkbox
devhatt/octopost pull request #413
Opened 2024-02-27 20:35 UTC by alvarogfn

2024-02-27 20:40 UTC, aalmeida00 submitted a review, later dismissed
faltou descrição do PR e também linkar issue.

2024-02-27 20:45 UTC, Felipeness submitted a review, later dismissed

2024-02-27 20:55 UTC, Felipeness approved these changes

2024-02-27 21:03 UTC, PiluVitu approved these changes

2024-02-27 22:06 UTC, aalmeida00 requested changes

2024-02-27 22:06 UTC, aalmeida00 commented on src/components/Checkbox/Checkbox.spec.tsx
> +    it('should mount input', async () => {
Should é redundante e repetitivo, remover pls

2024-02-28 00:19 UTC, aalmeida00 approved these changes

2024-02-28 01:00 UTC, merged