fix: replace tag button with button component
devhatt/octopost pull request #423
Opened 2024-03-01 18:24 UTC by JpBurgarelli

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

O intuito desse PR é substituir a TAG <button> pelo COMPONENTE <Button />.

  <summary>
    <b>Additional info</b>
  </summary>
Acho que esse componente não precisa de evidências visuais. 
</details>

2024-03-01 18:41 UTC, alvarogfn requested changes

2024-03-01 18:41 UTC, alvarogfn commented on src/components/SavBar/SavBar.tsx
> +function SavBar(): React.JSX.Element {
Utilizar o ReactNode ao invés do JSX.Element. O ReactNode já inclui casos como o JSX.element, mas também adiciona novas tipagens como null/arrays, etc. E não precisa importar o React inteiro, pode importar só o tipo

import { ReactNode } from "react";

function SavBar(): ReactNode

2024-03-01 18:59 UTC, alvarogfn approved these changes

2024-03-02 04:43 UTC, aalmeida00 requested changes

2024-03-02 04:43 UTC, aalmeida00 commented on src/components/SavBar/SavBar.tsx
mano, vamos aproveitar que estamos mexendo nesse componente, e trocar o nome dele?

SavBar, não dá! horrível, e trocar as classes css também.

2024-03-05 16:21 UTC, JpBurgarelli commented on src/components/SavBar/SavBar.tsx
Beleza. Deletei o nome ruim e renomei para ActionBar, conforme você recomendeu.

2024-03-05 16:41 UTC, JpBurgarelli commented
Essa task é um refactor, portanto o objetivo dela é fazer ajustes pontuais no antigo SavBar que agora passou a ser chamado de ActionBar. Além da mudança do nome, foi excluido, também, o SubmitBotton. Por fim, foram realizadas pequenas alterações no module.scss desse componente para ficar em harmonia as novas diretivas do projeto, como o path alias.

2024-03-05 17:06 UTC, Alecell requested changes

2024-03-05 17:06 UTC, Alecell commented on src/components/ActionBar/ActionBar.module.scss
>    a {
Muda isso aqui pra uma `class` ao inves de uma tag

2024-03-05 17:06 UTC, Alecell commented on src/components/ActionBar/ActionBar.module.scss
>    padding: 2rem;
Esse CSS todo faz sentido? Da uma revisada nele

2024-03-05 17:06 UTC, Alecell commented on src/components/ActionBar/ActionBar.tsx
> +      <Button> Save as draft</Button>
Ta faltando o outro botão

2024-03-05 17:06 UTC, Alecell commented on src/pages/home/home.tsx
>          <div className={scss.gridSavBar}>
Não é necessário esse wrapper, pode apagar

2024-03-05 21:01 UTC, JpBurgarelli commented on src/components/ActionBar/ActionBar.module.scss
>    a {
Mudado!

2024-03-05 21:02 UTC, JpBurgarelli commented on src/components/ActionBar/ActionBar.module.scss
>    padding: 2rem;
Realmente, após retira-lo, não fez diferença visual ou funcional.

2024-03-05 21:07 UTC, JpBurgarelli commented
Os botões continuam com a MESMA identidade visual, conforme projeto do Figma. O que foram alterados desde o ultimo push foi: adição dos buttons, nomes para as classes e buttons, pequenas estilizações no scss.
![image](https://github.com/devhatt/octopost/assets/30197026/0979f26b-9a9a-4c43-a0b2-99e9112b5a64)

2024-03-05 22:30 UTC, alvarogfn approved these changes

2024-03-06 16:36 UTC, aalmeida00 approved these changes

2024-03-06 17:18 UTC, Alecell submitted a review, later dismissed
MAS ajusta o role do CSS que comantamos na daily

2024-03-06 18:35 UTC, JpBurgarelli commented
Como o componente que agora chama ActionBar esta sendo importado dentro da Home e sendo envelopado por uma div, então, automaticamente essa Div se torna o wrapper do componente ActionBar, por isso tirei o max-width: 101rem, porque, agora, é usada div pai para delimitar o tamnho não há necessidade de eu manter o max-width, seria redudante. 

![image](https://github.com/devhatt/octopost/assets/30197026/182b98f7-fe8e-4dcb-8cbe-e008578aac6c)

2024-03-07 22:58 UTC, alvarogfn approved these changes

2024-03-08 01:52 UTC, aalmeida00 approved these changes

2024-03-09 14:59 UTC, merged