426 icon refactors
devhatt/octopost pull request #430
Opened 2024-03-06 20:04 UTC by Luiginicoletti

Esse PR resolvemos as seguintes issues abertas, algumas delas ainda

- [ ] #384  - A solucao deste componente depende da issue - [ ] #428 
- [ ] #359  - A solucao deste componente depende da issue - [ ] #429
- [x] #311 
- [x] #312 
- [x] #313 
- [x] #354

2024-03-10 19:47 UTC, Alecell requested changes
Apenas alguns ajustes no lint

2024-03-10 19:47 UTC, Alecell commented on src/components/AccordionTab/AccordionTab.tsx
> +      {hideCloseButton ? null : renderCloseButton()}
Não fazer isso e remover a regra que obriga esse ternário

2024-03-12 23:47 UTC, Luiginicoletti commented on src/components/AccordionTab/AccordionTab.tsx
> +      {hideCloseButton ? null : renderCloseButton()}
Resolvido

2024-03-12 23:47 UTC, Luiginicoletti commented on src/components/Accordion/Accordion.tsx
> +        ) : null}
Resolvido

2024-03-18 21:05 UTC, Alecell requested changes
Algumas cosias não estão resolvidas aqui

2024-03-18 21:05 UTC, Alecell commented on src/components/Accordion/Accordion.tsx
> +        ) : null}
ué mas ainda ta o ternario com null aqui ;-;

2024-03-18 21:05 UTC, Alecell commented on src/components/AccordionTab/AccordionTab.tsx
> +      {hideCloseButton ? null : renderCloseButton()}
Ele ainda ta aqui ;-;

2024-03-19 12:20 UTC, hxsggsz commented on src/components/Accordion/Accordion.tsx
> +function computeVariants(duration: number): Record<string, Variant> {
isso é pra ter autocomplete nas propiedades do framer motion? que pica parabens, fiquei muito tempo procurando isso e nunca consegui

2024-03-19 12:24 UTC, hxsggsz approved these changes
tirando o detalhe que eu comentei e os apontamentos do ale acho que ta bala

2024-03-19 12:24 UTC, hxsggsz commented on src/components/AccordionTab/AccordionTab.tsx
> +    <button className={scss.closeButton} onClick={handleClose} type="button">
```suggestion
    <button className={scss.closeButton} onClick={handleClose>
```
esse `type="button"` não é necessário se você usa o html `button` ele só serve pra fazer atrocidades tipo usar div como button

2024-03-19 12:24 UTC, hxsggsz commented on src/components/Modal/Modal.tsx
> +                <button onClick={props.onClickOutside} type="button">
```suggestion
                <button onClick={props.onClickOutside}>
```
esse type="button" não é necessário se você usa o html button ele só serve pra fazer atrocidades tipo usar div como button

2024-03-19 16:36 UTC, Luiginicoletti commented on .eslintrc.cjs
> -    'jsx-a11y/click-events-have-key-events': 'warn',
Adicionei novamente.

2024-03-19 16:36 UTC, Luiginicoletti commented on .eslintrc.cjs
> -    'jsx-a11y/no-static-element-interactions': 'warn',
Adicionei novamente.

2024-03-19 16:39 UTC, Luiginicoletti commented on src/components/Accordion/Accordion.tsx
> +function computeVariants(duration: number): Record<string, Variant> {
^^

2024-03-19 16:40 UTC, Luiginicoletti commented on src/components/AccordionTab/AccordionTab.tsx
> +    <button className={scss.closeButton} onClick={handleClose} type="button">
O pessoal estava aqui na call na hora que eu estava lendo e disseram que tem mais funcoes nisso, e disseram que e bom deixar.

2024-03-19 16:40 UTC, Luiginicoletti commented on src/components/Modal/Modal.tsx
> +                <button onClick={props.onClickOutside} type="button">
O pessoal estava aqui na call na hora que eu estava lendo e disseram que tem mais funcoes nisso, e disseram que e bom deixar.

2024-03-19 16:41 UTC, Luiginicoletti commented on src/components/AccordionTab/AccordionTab.tsx
> +      {hideCloseButton ? null : renderCloseButton()}
Nao sei por que apareceu novamente, pois isso ja havia sido resolvido, de qualquer forma resolvi novamente.

2024-03-19 16:41 UTC, Luiginicoletti commented on src/components/Accordion/Accordion.tsx
> +        ) : null}
Resolvido novamente.

2024-03-19 16:43 UTC, Luiginicoletti commented
Todos os problemas no codigo foram resolvidos novamente porem meu codigo nao esta passando no CI/CD seguintes e necessito de ajuda pois a resolucao disto ficou complexo demais para mim.

Code Style / code-style (pull_request)
Node.js CI / build (pull_request)

2024-05-04 17:15 UTC, alvarogfn approved these changes

2024-05-04 17:20 UTC, Alecell approved these changes

2024-05-05 19:38 UTC, Alecell approved these changes

2024-05-05 20:59 UTC, hxsggsz commented on electron/main.ts
> +        await win.loadFile(path.join(process.env.DIST, 'index.html'));
isso aqui ta paia, código comentado e if dentro de else

2024-05-05 20:59 UTC, hxsggsz commented on src/components/AccordionTab/AccordionTab.spec.tsx
> -
isso era pra corrigir um erro na hora de testar o accordion por causa do framer motion, o erro do teste ainda não ta acontecendo sem esse beforeEach?

2024-05-05 21:01 UTC, zoldyzdk approved these changes

2024-05-06 01:51 UTC, Alecell commented on src/components/AccordionTab/AccordionTab.spec.tsx
> -
Não ta, o test passa \o/

2024-05-06 01:53 UTC, Alecell commented on electron/main.ts
> +        await win.loadFile(path.join(process.env.DIST, 'index.html'));
O comentário eu removi, o dentro de if e else foi só pra parar o erro de que os envs podiam ser undefined.

Vamos revisitar essa camada toda novamente, como ela ta faznedo oque precisa resolver que é expor o web no electron vamos deixar assim por now

2024-05-06 01:55 UTC, merged