Issue 434 - Corrigir problemas com componentes no ladle
devhatt/octopost pull request #436
Opened 2024-03-12 03:07 UTC by Sherlockzen

Closes #434 

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  Componentes com problema quebrando no ladle.

- **Cause**
  Houveram mudanças em alguns componentes, como o Icon, que afetaram outros componentes e estes estavam quebrando quando testados no ladle do projeto.

- **Solution**
Verifiquei os seguintes componentes e corrigi o suficiente para que sejam executados no ladle e visualizados:
  * Button
  * Compose Editor
  * Feedback error
  * Tabber
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>

![image](https://github.com/devhatt/octopost/assets/90076846/4db032d1-bf79-43ff-a135-c5976b232962)
![image](https://github.com/devhatt/octopost/assets/90076846/2f103262-6171-45df-a36b-5f8b54b0fde2)
![image](https://github.com/devhatt/octopost/assets/90076846/dca210fb-2000-4fa3-84e3-45ae0733b8e7)
![image](https://github.com/devhatt/octopost/assets/90076846/f315609f-9d15-4c4b-b72b-bb8c30d51bbc)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>
É importante destacar que foi realizado ajustes básicos para que os componentes renderizassem corretamente no ladle, não foi feito refatoração completa deles. Para isso há uma task de todo #414 a qual lista os componentes que precisam de refatoração, sendo que cada componente pode virar uma task exclusiva
</details>

2024-03-12 15:51 UTC, alvarogfn requested changes

2024-03-12 15:51 UTC, alvarogfn commented on src/components/Button/Button.stories.tsx
> +    <Button circle icon={<Icon icon="alert" width={32} />} />
Não precisa criar todos os botões em um mesmo story.

Crie stories diferentes para botões diferentes ou configure eles para serem ajustados via props.

2024-03-12 15:51 UTC, alvarogfn commented on src/components/Tabber/Tabber.tsx
> +            <preview.previewComponent
Desestrutura esse previewComponent do preview e usa Pascal Case pra escrever o componente

2024-03-12 19:48 UTC, Alecell requested changes

2024-03-12 19:48 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.module.scss
> +  width: 20px;
use outra unidade nesse caso

2024-03-12 19:48 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +// import { useMediaQuery } from '~hooks/useMediaQuery/useMediaQuery';
remova o comentário

2024-03-12 23:47 UTC, Sherlockzen commented on src/components/Tabber/Tabber.tsx
> +            <preview.previewComponent
Man é o seguinte, o componente de Tabber tá sendo todo refatorado pelo Wellington então eu não queria mexer muito saca? Porque ai seria retrabalho porque ele ta todo por dentro desse componente. Faz sentido?? Inclusive esse cód tem no pr dele.

2024-03-12 23:53 UTC, Sherlockzen commented on src/components/FeedbackError/FeedbackError.module.scss
> +  width: 20px;
Resolvido!

2024-03-12 23:55 UTC, Sherlockzen commented on src/components/Tabber/Tabber.tsx
> +// import { useMediaQuery } from '~hooks/useMediaQuery/useMediaQuery';
Removido!

2024-03-13 13:48 UTC, Sherlockzen commented on src/components/Button/Button.stories.tsx
> +    <Button circle icon={<Icon icon="alert" width={32} />} />
Pronto, criado meu amigo, código muito mais limpo agora, obrigado!

2024-03-13 13:58 UTC, alvarogfn approved these changes

2024-03-15 13:41 UTC, Alecell approved these changes

2024-03-15 13:41 UTC, merged