refactor: add new style to FeedBackError & update the icon
devhatt/octopost pull request #438
Opened 2024-03-14 10:16 UTC by JpBurgarelli

Closes #374 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Foram realizados ajustes Estilísticos no Componente para ficar em conformidade com o novo Layoput. A primeira imagem representa o layout do figma e o que está em baixo ( outra imagem e vídeo ) o resultado.  
Para isso foram adicionados novos códigos e, também, estilizações. Foi preciso adicionar o novo icone da nossa lib de icones ("Alert" ) e tive que adiconar o icone que nomei como "DropDownArrow"  que representa a setinha com para baixo.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/30197026/031213c7-5d86-4a74-a3b0-af5007f02625)

![image](https://github.com/devhatt/octopost/assets/30197026/34885bd4-d48c-4415-98e8-aed546566bce)

https://github.com/devhatt/octopost/assets/30197026/b9619f6f-192d-4e57-858a-bfceeca7a866

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
- [X] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Foi removida uma regra de Lint que ja tinha sido removida antes  que impede a utilização do operador lógico &&
</details>

2024-03-14 10:57 UTC, alvarogfn reviewed
Dá um up nesse componente como um todo. Melhora o coverage dele para 100%, arruma os stories e o types. 

Pega o exemplo do componente de [Avatar](https://github.com/devhatt/octopost/blob/077ee84e4e6d44f4eebb958961873c771a4d00d4/src/components/Avatar/Avatar.tsx).

2024-03-15 15:37 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.module.scss
> +    line-height: 2rem;
`line-height` não usa nenhuma unidade

2024-03-15 15:37 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.module.scss
> +      line-height: 2rem;
Não usa unidade

2024-03-15 15:42 UTC, Alecell requested changes
Alguns ajustes e atualiza a branch

2024-03-15 15:42 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.tsx
> +        {renderErrorDropdown()}
Coloque aquele `if` aqui

2024-03-17 12:37 UTC, JpBurgarelli commented
No último commit, fiz ajustes pontuais na estilização e na condição (if) dentro do meu arquivo.

2024-03-17 23:50 UTC, hxsggsz requested changes

2024-03-17 23:50 UTC, hxsggsz commented on src/components/FeedbackError/FeedbackError.tsx
> +          </div>
um componente de icone com função de onClick não é semantico, transforma a div em volta dele em um button e coloca a função de onclick nela

2024-03-17 23:50 UTC, hxsggsz commented on src/components/FeedbackError/FeedbackError.tsx
> +              onClick={() => setShowErrors(!showErrors)}
``
```suggestion
              onClick={() => setShowErrors((prevState) => !prevState)}
```

2024-03-17 23:50 UTC, hxsggsz commented
ta faltando adicionar os testes dessa lista nova de erros

2024-03-19 00:51 UTC, Alecell requested changes
Um pequeno ajuste!

2024-03-19 00:51 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.tsx
> +  return <AnimatePresence>{errorMessage && renderError()}</AnimatePresence>;
Isso ta ruim, vc ta animando algo que pode nem aparecer, a condição precisa estar um nível lógico a cima, renderizando a animação apenas quando necessário

2024-03-19 01:40 UTC, JpBurgarelli commented
Segundo o @Alecell, o trecho   "return <AnimatePresence>{errorMessage && renderError()}</AnimatePresence>; " estava ruim, pois  estava sendo animado algo que podia nem mesmo aparecer, sendo a animação renderizada apenas quando necessário, portanto eu fiz um ternário  ( "  return errorMessage ? renderError() : null; " ) que verifica se há um mensagem de erro e, caso haja, a estrutura do componente de erro é chamada com o  AnimatePresence, ou seja, apenas será animado, se for chamado. 

https://github.com/devhatt/octopost/assets/30197026/d46d0e00-0a23-4cd1-9124-e77079b690ba

2024-03-19 19:53 UTC, hxsggsz requested changes
um detalhe só e os testes paizao, precisa atualizar os testes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2024-03-19 19:53 UTC, hxsggsz commented on src/components/FeedbackError/FeedbackError.tsx
> +  return errorMessage ? renderError() : null;
```suggestion
  return errorMessage && renderError();
```
o problema pro ale ai nao era o `if ternário`, era o lugar do `AnimatedPresence`

2024-03-21 20:16 UTC, JpBurgarelli commented
No último commit, foram feitas alterações lógicas no componente FeedbackError, já que agora, seguindo o layout, temos uma mensagem de erro padrão e dentro do DropDown teremos a indicação dos respectivos erros. Para isso, alterações tiveram que ser feitas em todo o componente useError (que é um componente que utiliza o Zustand para criar um Hook personalizado responsável por receber os erros e atualizar a lista de erros).

2024-03-25 15:09 UTC, hxsggsz requested changes

2024-03-25 15:09 UTC, hxsggsz commented on src/components/FeedbackError/FeedbackError.tsx
> +              Failed to progress, please click on the<strong> button </strong>on
evita usar tags que alterem o estilo do layout, deixa essa responsabilidade com o css, troca esse `strong` por uma `span` e passa o css pra deixar o texto dentro da span em `bold`

2024-03-25 15:09 UTC, hxsggsz commented on src/stores/useError/useError.spec.ts
> +  const zustandd = await vi.importActual('zustand');
```suggestion
  const zustand = await vi.importActual('zustand');
```
typo na variavel

2024-03-25 15:09 UTC, hxsggsz commented on src/stores/useError/useError.spec.ts
>      });
por que a mudança do forEach pro for?

2024-03-25 16:39 UTC, Alecell reviewed
Cade o teste do componente? Vc só testou o hook

2024-03-25 16:39 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.stories.tsx
> +};
Esse tipo não deve ser definido aqui

2024-03-25 16:39 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.stories.tsx
> +  }, [props.errors, setErrors]); // Include 'setErrors' in the dependency array
Apagar o comentário

2024-03-25 16:39 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.tsx
> +              Failed to progress, please click on the<strong> button </strong>on
Essas tags são boas pra SEO, mas realmente seus estilos devem ser resetados para não alterarem o estilo e tambem nao precisamos de SEO nos erros

2024-03-25 16:39 UTC, Alecell commented on src/stores/useError/useError.spec.ts
>      });
Porque precisamos desse act?

2024-03-25 16:39 UTC, Alecell commented on src/stores/useError/useError.spec.ts
> +    it('errors array is empty', () => {
esse expressão não faz sentido, seria `it('has a empty error array')`

2024-03-25 16:39 UTC, Alecell commented on src/stores/useError/useError.spec.ts
> +      expect(result.current.errors).toEqual(['new error message']);
Não sei se esse testa ta eficiente, parece que ele nao testa nada

2024-03-27 19:22 UTC, JpBurgarelli commented
O ultimo commit foi responsável por adicionar o teste do componente feedbackError.

2024-03-27 19:27 UTC, Alecell requested changes
Ajustes no teste

2024-03-27 19:27 UTC, Alecell commented on package.json
Pq isso voltou/

2024-03-27 19:27 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.type.ts
Porque temos esse type aqui? Acredito que nao precisamos

2024-03-28 11:41 UTC, Alecell reviewed
Sobre os testes do zustand em si, verifica meus comentários que já tão aqui, mas basicamente oque precisamos fazer agora é testar se o estado do `errors` de dentro do hook funciona depois do método ser chamado.

Inclusive acabei de pensar que precisa de um método de remover erro!

2024-03-28 11:41 UTC, Alecell commented on src/components/FeedbackError/FeedbackError.module.scss
> +    .wrapperErrorList li {
Não usar tag diretamente, usar classes

2024-03-28 14:51 UTC, hxsggsz approved these changes

2024-04-15 19:52 UTC, hxsggsz approved these changes

2024-04-16 09:00 UTC, zoldyzdk requested changes

2024-04-16 09:00 UTC, zoldyzdk commented on src/components/FeedbackError/FeedbackError.type.ts
>  export type IFeedbackErrorProps = {
`export type TFeedbackErrorProps`

2024-04-16 09:00 UTC, zoldyzdk commented on package.json
> +    "eslint-plugin-write-good-comments": "0.2.0",
Essa regra tinha sido removida, porque voltou?

2024-04-16 09:00 UTC, zoldyzdk commented on src/stores/useError/useError.ts
> +      errors: { ...state.errors, [id]: { id, message: newErrorMessage } },
Não entendi porque o `id` é duplicado no objeto de `errors` acho que um dos dois não precisaria existir.

2024-04-16 18:25 UTC, zoldyzdk approved these changes

2024-04-16 19:16 UTC, hxsggsz approved these changes

2024-04-17 17:20 UTC, merged