Issue 373
devhatt/octopost pull request #441
Opened 2024-03-18 19:08 UTC by ViniFerreiraL

Closes #373 

- **Description**
Retirei  a regra [write-good-comments/write-good-comments](https://github.com/kantord/eslint-plugin-write-good-comments) do eslint e subestitui pelos chamadas do enum para que sejam iguais a declaração EHttpStatusCode

2024-03-19 12:30 UTC, alvarogfn commented
Vc apontou sua pr pra branch errada, era pra apontar pra master do octopost

2024-03-19 16:14 UTC, alvarogfn approved these changes

2024-03-19 16:43 UTC, alvarogfn requested changes
Remove o plugin write-good-comments e desinstala o pacote eslint-plugin-write-good-comments do package.json

2024-03-19 17:48 UTC, Sherlockzen approved these changes

2024-03-25 13:43 UTC, PiluVitu approved these changes

2024-03-25 13:59 UTC, merged