Error Boundary - Issue 383
devhatt/octopost pull request #449
Opened 2024-03-26 15:13 UTC by Sherlockzen

Closes #383 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Remoção do componente de ErrorBoundary próprio e adição do componente vindo do Sentry.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
<br/>
<b> ErrorBoundary aplicado no Octopost e retornando uma fallback quando encontra erros no app.</b>
<br/>

![image](https://github.com/devhatt/octopost/assets/90076846/d4466f7e-df63-4ba1-8c96-a448360b30a4)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Não temos um layout de página de erro genérica pra servir de fallback pro ErrorBoundary.
</details>

2024-03-27 14:23 UTC, PiluVitu approved these changes

2024-03-27 14:29 UTC, diogocaronte requested changes

2024-03-27 14:29 UTC, diogocaronte commented on .gitignore
> +.idea
```suggestion
.idea

```

2024-03-27 14:33 UTC, diogocaronte approved these changes

2024-03-27 14:34 UTC, PiluVitu approved these changes

2024-03-28 11:49 UTC, Alecell reviewed
Só quero entender uma coisa antes, até onde me consta um error boundary de respeito deveria dar catch() nos erros estourados e não lotar o console de erro. Isso não ta acontecendo pq?

2024-03-28 14:57 UTC, Sherlockzen commented
> Só quero entender uma coisa antes, até onde me consta um error boundary de respeito deveria dar catch() nos erros estourados e não lotar o console de erro. Isso não ta acontecendo pq?
@Alecell 

Pelo que  eu vi e testei isso não é uma característica do próprio ErrorBoundary. Na documentação do React não faz referência a isso e por exemplo o componente já pronto que eles recomendam ([react-error-boundary](https://github.com/bvaughn/react-error-boundary)) também mostra os erros no console.

Pesquisando mais a fundo achei essa [issue](https://github.com/facebook/react/issues/15069) e nela tem essa resposta do próprio Dan Abramov falando que preferiram não inserir essa opção porque pode facilmente "engolir" erros:

![image](https://github.com/devhatt/octopost/assets/90076846/79e845aa-7305-41d6-b678-b16aba072606)

Também fui testar como o [Nextjs](https://nextjs.org/docs/app/building-your-application/routing/error-handling) fazia esse tipo de error handling mais genérico com o ErrorBoundary, e ele também mostra o erro no console, mesmo implementando o `Error.tsx` que vai usar do ErrorBoundary pra capturar os erros e mostrar uma fallback ui ao invés de quebrar a aplicação.

2024-03-28 15:10 UTC, Alecell approved these changes

2024-03-28 15:10 UTC, merged