Issue 429
devhatt/octopost pull request #450
Opened 2024-03-26 21:27 UTC by TheGzuckert

Closes #429 

<details open> 
  <summary>
    <b>Feature</b>
      Ajustei o componente button tentando seguir o mais próximo possível do design do Figma, entretanto durante o desenvolvimento acabei mexendo também no componente Submit button.
      Caso precise que de rollback sem problema.
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>

 Componente Button:
![image](https://github.com/devhatt/octopost/assets/83929799/c9ae7289-7080-4789-9f32-a500ebec72de)
 
 Componente: Submit Button
![image](https://github.com/devhatt/octopost/assets/83929799/079da45f-2ce1-4b32-9465-7c5b2606c9f6)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-03-28 14:46 UTC, hxsggsz commented
seu pr ta apontando pra branch errada, é pra apontar pra main e tem commits de outras pessoas no teu pr, tem que dar uma olhada nisso ai

2024-03-28 17:04 UTC, TheGzuckert commented
Aaah sim sim hx vou corrigir isso

2024-04-19 14:59 UTC, hxsggsz requested changes

2024-04-19 14:59 UTC, hxsggsz commented on src/components/Button/Button.module.scss
> +@use '../../styles/global';
usa o path alias aqui, da uma olhada nos outros arquivos de scss pra ver como é

2024-04-19 14:59 UTC, hxsggsz commented on src/components/Button/Button.module.scss
>  @mixin outlined($color, $border, $hover) {
os parametros que nao tao sendo usandos nao precisa mais? faz sentido nao usar eles? se sim remove da função, acho que vale a pena dar uma olhada nisso

2024-04-19 14:59 UTC, hxsggsz commented on src/components/Button/Button.module.scss
> +
importa as coisas do global usando o `as *` pra nao precisar colocar esse global na frente, esse é o padrao que a gente usa no octopost

2024-04-19 14:59 UTC, hxsggsz commented on src/components/Button/Button.module.scss
> +        color: global.$secondaryGray;
mesma coisa do comentário de cima

2024-04-19 14:59 UTC, hxsggsz commented on src/components/SubmitButton/SubmitButton.module.scss
>    background-color: global.$primaryWhite;
faz o que eu falei do comentario acima em todos `global.`

2024-04-19 14:59 UTC, hxsggsz commented on src/components/SubmitButton/SubmitButton.module.scss
> +  border: 0.1rem solid global.$secondaryGray;
borda é legal passar um valor fixo com px

2024-04-19 15:03 UTC, TheGzuckert commented
@hxsggsz Acredito que eu tenha conseguido colocar o link da issue, pode olhar de novo por favor

2024-04-19 15:21 UTC, hxsggsz commented
seria bom tambem adicionar alguns testes pro componente de botao e o submitButton que voce criou tambem

2024-04-23 14:37 UTC, Alecell requested changes
Acho q vacilamos em uma coisa, o botão deveria ser o já existente!

2024-04-23 14:37 UTC, Alecell commented on src/components/Button/Button.module.scss
>  button {
Não usar seletores de tag, usar apenas classes

2024-04-23 14:37 UTC, Alecell commented on src/components/Button/Button.module.scss
> +  height: 4.65rem;
isso é basicam ente uma width e height fixa, isso não pode existir, usar valroes relativos ou pelo menos um min-width. Mas não especifique a height de qualquer forma

2024-04-23 14:37 UTC, Alecell commented on src/components/SubmitButton/SubmitButton.module.scss
> +  height: 5rem;
Não defina height fixa. Nunca

2024-04-23 14:37 UTC, Alecell commented on src/components/SubmitButton/SubmitButton.module.scss
> +.submitButtonPostLater:disabled {
Sei que já estavam, mas renomeia essas classes o nome ta muito ruim

2024-04-23 14:37 UTC, Alecell commented on src/components/SubmitButton/SubmitButton.tsx
> +      </button>
use o componente de Button já existente no projeto, não era pra criar outro!

2024-04-23 17:37 UTC, TheGzuckert commented on src/components/SubmitButton/SubmitButton.tsx
> +      </button>
Pior que eu não criei o componente SubmmitButton, ele já existia

![image](https://github.com/devhatt/octopost/assets/83929799/adc724b3-e0a6-4518-bf4d-4e14501e3a7d)

2024-04-26 16:49 UTC, hxsggsz submitted a review, later dismissed

2024-05-01 12:40 UTC, Alecell commented on src/components/SubmitButton/SubmitButton.tsx
> +      </button>
Ai aproveita e ajusta u.u

2024-05-01 23:28 UTC, TheGzuckert commented on src/components/SubmitButton/SubmitButton.tsx
> +      </button>
Ta ajustado U.u

2024-05-06 22:21 UTC, Alecell requested changes
Acho que talvez escrevi mal a task, precisamos rever algumas coisas aqui

2024-05-06 22:21 UTC, Alecell commented on src/components/Button/Button.module.scss
> +  max-width: 15rem;
Um componente de button não pode ter um limite assim chumbado em si mesmo, a menos que fosse algum outro componente definindo isso. 

Aqui acredito que o ideal é um `width: 100%`, assim quem define o tamanho que o botão será é que usar ele, não o botão em si

2024-05-06 22:21 UTC, Alecell commented on src/components/SubmitButton/SubmitButton.module.scss
Esse componente não existe, pode apagar, não existe diferença entre um submit button e um button, só muda o uso em si, mas todas as variações desejadas ao `SubmitButton` ja devem ser atendidas pelo `Button`

2024-05-06 22:21 UTC, Alecell commented on src/components/SubmitButton/SubmitButton.tsx
> +      </button>
No caso aqui precisamos usar o componente `Button`, não usar o `button` nativo do HTML e aplicar estilos, o `<Button>` é o componente que vai resolver isso pra gente!

2024-05-13 18:41 UTC, TheGzuckert commented on src/components/SubmitButton/SubmitButton.module.scss
Removido

2024-05-13 19:16 UTC, TheGzuckert commented on src/components/Button/Button.module.scss
> +  max-width: 15rem;
Aplicando o _width: 100%_ o componente ficou assim:

![image](https://github.com/devhatt/octopost/assets/83929799/4daad263-55f5-44e7-98af-cbff2d936794)

Está correto?

2024-05-14 11:49 UTC, Alecell requested changes

2024-05-14 11:49 UTC, Alecell commented on src/components/Button/Button.module.scss
>  button {
Esse comentario nao foi resolvido ainda. o `button` tem que ser uma classe, nem que seja `.button`

2024-05-14 11:52 UTC, Alecell commented on src/components/Button/Button.module.scss
> +  max-width: 15rem;
Sim, quem determina o tamanho que o botao tem q ter é quem usa

2024-05-14 15:01 UTC, hxsggsz approved these changes

2024-05-14 19:28 UTC, TheGzuckert commented on src/components/Button/Button.module.scss
>  button {
acabei deixando passar perdão alee

2024-05-14 20:33 UTC, hxsggsz approved these changes

2024-05-15 17:50 UTC, Alecell approved these changes

2024-05-16 01:49 UTC, hxsggsz approved these changes

2024-05-16 01:49 UTC, merged