fix: some stuffs
devhatt/octopost pull request #451
Opened 2024-03-28 15:26 UTC by Luiginicoletti

Closes [] - #380 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

- Renomear o componente para um nome mais generico.
Renomeei para CustomInput, pois achei bem generico.
- Alterar a chamada dos componentes de icone antigo para seguir o novo padrão do componente de icone.
Foram feitos as alteracoes para o novo componente de Icon
- Placeholder vir por props
Esta vindo via props
- iconLeft e iconRight devem ser definidos por props
Por enquanto nao fizemos esses pois teria que mudar toda logica deixaremos pra quando precisar.
- Verificar se o componente é hibrido, ou seja, ele deve suportar ser controlled e uncontrolled
hibrido

- O placeholder do texto está desalinhado verticalmente, existe mais espaço em baixo do que em cima, precisa centraliza-los
- Ajustar o tamanho da tag interna, a que possui o padding, ela não está na mesma altura do seu elemento pai
visualmente parece estar certo.

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-07 22:56 UTC, aalmeida00 commented on src/components/CustomInput/CustomInput.tsx
> +export const CustomInputRef = forwardRef(CustomInput);
Cara esse nome ficou ruim.

nao é melhor só exportar default como customInput?;

2024-04-07 22:56 UTC, aalmeida00 commented on src/components/CustomInput/CustomInput.tsx
> +          <Icon icon="mag" />
Se o icone aqui for mag sempre, ele nao vai poder ser mudado nao?

2024-05-01 14:28 UTC, hxsggsz requested changes

2024-05-01 14:28 UTC, hxsggsz commented on src/components/CustomInput/CustomInput.tsx
>      >
se é clicavel precisa ser um `button` pela questão de acessibilidade
```suggestion
    <button
      className={scss.iconRight}
      data-testid="clear-button"
      onClick={handleClear}
    >
```

2024-05-01 14:28 UTC, hxsggsz commented on src/components/CustomInput/CustomInput.tsx
> +      {error ? <Icon icon="alert" /> : <Icon icon="close" />}
nesse caso você só ta trocando o icone caso tenha erro mas se clicar ele vai apagar o texto igual o icone de close, acho que aqui talvez seja o ideal concatenar um button com o onclick e o icone de close e uma div com o icone de erro e sem o onclick do button

2024-05-01 14:28 UTC, hxsggsz commented on src/components/CustomInput/CustomInput.tsx
>      if (props.onFocus) props.onFocus(event);
no handle value voce ta fazendo `props.onChange?.(e.target.value)` e aqui ta fazendo `if (props.onFocus) props.onFocus(event)` os dois estão certos e fazem a mesma coisa mas estão fora de padrão, escolhe um dos dois e padroniza pra todos

2024-05-01 14:28 UTC, hxsggsz commented on src/components/CustomInput/CustomInput.tsx
>    }
mesma coisa aqui pro negócio dos padrões do ultimo comentário

2024-05-01 14:28 UTC, hxsggsz commented on src/components/CustomInput/CustomInput.tsx
>            onBlur={(e) => onInputBlur(e)}
nesse caso nao precisa passar explicitamente o evento pra função, o react ja faz isso implicitamente pra gente
```suggestion
          onBlur={onInputBlur}
```

2024-05-01 14:28 UTC, hxsggsz commented on src/components/CustomInput/CustomInput.tsx
> +          type={props.type}
você pode usar o `spread` pra essas props que são padrões do input pra facilitar a vida, assim quem usar esse componente vai ter acesso as props que você criou + as props nativas de um input, incluindo as que você não passou aqui
```suggestion
         {...props}
```

2024-06-25 12:44 UTC, closed without merging