Adjust social accordion#365
devhatt/octopost pull request #473
Opened 2024-04-18 17:54 UTC by Felipeness

Closes #365 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Implementação do componente `SocialAccordion` para diferentes mídias sociais. Suporta a visualização e interação com contas de mídias sociais como Facebook, Instagram e Twitter, permitindo expansão e contração dos detalhes da conta, ajuste para melhor aproximação ao conceito do figma. 

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  Ajuste dos tipos TypeScript para o componente `SocialAccordion`, garantindo compatibilidade com a estrutura de dados esperada.

- **Cause**
  Incompatibilidade entre a estrutura de dados do mock e a definição dos tipos TypeScript causou falhas no uso do componente.

- **Solution**
  Ajuste nos tipos `ISocialAccordion` e criação de mocks específicos para cada rede social, garantindo a correta passagem de dados para o componente.

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

- Implementação do `SocialAccordion` com suporte para múltiplas mídias sociais.
- Correção nos tipos TypeScript para alinhar com a estrutura de dados de mocks.
- Correção do SCSS do SocialAccordion e do AccountCard

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created

</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

Implementação inicial suporta Facebook, Instagram, e Twitter, com possibilidade de expansão para outras plataformas no futuro. Necessario no futuro mexer no sidebar, não ficou 100% igual o figma devido o sidebar tem alguns SCSS não correspondentes. 

</details>

2024-04-18 21:11 UTC, zoldyzdk requested changes

2024-04-18 21:11 UTC, zoldyzdk commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +export type ISocialAccordion = {
Ajusta esse prefixo ai paizão

2024-04-18 21:11 UTC, zoldyzdk commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +export type IAccountList = {
Ajusta esse prefixo ai paizão

2024-04-18 21:15 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +export type IAccountList = {
Ajustar o que paizão? Ja tava assim, só mudei de interface para type

2024-04-19 16:59 UTC, zoldyzdk approved these changes

2024-04-24 00:26 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
Ao invés de ficar usando o  `screen.getByText`  dessa forma, que tal melhorar um pouco e já desestruturar direto?

Fazer algo do tipo direto

```
  const { getByText } = render(
      <SocialAccordion
        accountList={mockList}
        error={false}
        socialMediaName="facebook"
      />
    );
    
    expect(getByText(/facebook/i)).toBeInTheDocument();
    ```

2024-04-24 00:26 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.stories.tsx
> +export const SocicialAccordionComponent: Story<TSocialAccordion> = (props) => (
Esse erro nao foi seu, mas tem um erro de typo nesse storie
```suggestion
export const SocialAccordionComponent: Story<TSocialAccordion> = (props) => (
```

2024-04-24 00:26 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/mockFacebookData.ts
A gente poderia juntar esses 3 arquivos de mock em um só nao? E exportar eles pro import ficar melhor.

2024-04-24 00:26 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/assets/instagram.svg
Será que ao invés de usar esse svg e colocar no projeto, nao poderiamos usar um dos nossos ícones?

2024-04-24 00:36 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/mockFacebookData.ts
Tentei, mas ele só aceita um mock de cada vez. 

Vou te chamar em call para você me ensinar depois

2024-04-24 00:36 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.stories.tsx
> +export const SocicialAccordionComponent: Story<TSocialAccordion> = (props) => (
Deixei passar, sorry sorry

2024-04-24 00:37 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
True , irei fazer melhor

2024-04-24 00:37 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/assets/instagram.svg
Tava testando com svg, o Ale pediu para esperar os outros ícones, mas vou usar os nossos agora

2024-04-25 22:47 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/mockFacebookData.ts
![image](https://github.com/devhatt/octopost/assets/61947632/569149df-53ea-47be-9a77-d64e6d6f93d7)

2024-04-25 22:47 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/mockFacebookData.ts
![image](https://github.com/devhatt/octopost/assets/61947632/a2791e85-a5be-4aaa-aa6d-7c11e8664e9c)

2024-04-25 22:48 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/mockFacebookData.ts
Tem que fazer isso pai.

Juntar os mocks em um arquivo só
E ajustar os imports.

2024-04-26 02:33 UTC, aalmeida00 commented
Ajustar os conflitos!

2024-04-30 13:23 UTC, Alecell requested changes

2024-04-30 13:23 UTC, Alecell commented on src/components/AccountCard/AccountCard.module.scss
> +  width: 26.8rem;
Não usar `width` fixa

2024-04-30 13:23 UTC, Alecell commented on src/components/AccountCard/AccountCard.module.scss
> +
Apagar espaço

2024-04-30 13:23 UTC, Alecell commented on src/components/AccountCard/AccountCard.module.scss
>    display: -webkit-box;
Esse formato de display deveria ser alterado

2024-04-30 13:23 UTC, Alecell commented on src/components/AccountCard/AccountCard.module.scss
>    -webkit-line-clamp: 1;
isso aqui tambem acho que poderia ir embora

2024-04-30 13:23 UTC, Alecell commented on src/components/AccountCard/AccountCard.module.scss
> +  justify-content: center;
Isso tem o problema do vídeo que mandei no grupo do whats, no fim do dia esse `width` fixa espremer e sair do layout em tamanhos pequenos

2024-04-30 13:23 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
>    p {
Não usar tag pura em CSS

2024-04-30 13:23 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
> +  p {
Não usar tag pura em css

2024-04-30 13:23 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
>  @use '../../../../../../styles/global' as *;
Ajustar path alias

2024-04-30 13:23 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
> +    height: 1.2rem;
`width` e `height` fixa não deveria existir nesse caso

2024-04-30 13:23 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
> +    justify-content: center;
To com a sensação que o stylelint não ta funcionando no seu ambiente, ele ta?

2024-04-30 13:23 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
>  import Accordion from '../../../../../../components/Accordion/Accordion';
Usar path alias

2024-05-02 11:05 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
> +  p {
nesse caso não sei não usar, pois o componente renderiza apartir de outras propriedades span e p.

2024-05-02 11:05 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
>  @use '../../../../../../styles/global' as *;
ajustado, sorry sorry

2024-05-02 11:05 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
>  import Accordion from '../../../../../../components/Accordion/Accordion';
ajustado

2024-05-02 11:09 UTC, Felipeness commented on src/components/AccountCard/AccountCard.module.scss
>    display: -webkit-box;
alterado para flex com   white-space: nowrap;
  text-overflow: ellipsis; 
  
  mantendo assim o que o web kit box faz

2024-05-02 11:09 UTC, Felipeness commented on src/components/AccountCard/AccountCard.module.scss
> +
erro de lf crlf, ajustado

2024-05-02 11:31 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.module.scss
> +    height: 1.2rem;
mas é como o icon funciona, eu passo a propriedade para o icon atraves do class ou tag que ele está, se eu removo isso o icon simplesmente fica muito grande ou some.

2024-05-02 13:58 UTC, Felipeness commented on src/pages/home/components/Sidebar/components/SocialAccordion/mockFacebookData.ts
vlw

2024-05-06 21:57 UTC, Alecell commented
Vou revisar quando atualizar a branch!

2024-05-21 01:42 UTC, alvarogfn submitted a review, later dismissed

2024-05-21 02:35 UTC, zoldyzdk requested changes

2024-05-21 02:35 UTC, zoldyzdk commented on src/components/AccountCard/AccountCard.tsx
>        {/* TODO: [2025-04-01]: Replace this button for a <IconButton /> with star icon after #392 */}
Remove o TODO

2024-05-21 02:35 UTC, zoldyzdk commented on src/pages/home/components/Sidebar/components/SocialAccordion/mocksMidiaData.ts
> +const mockTwitterAccounts: StoreAccount[] = [
Esses mocks não deveriam ser o service que o Alecell fez?

2024-05-26 20:41 UTC, Alecell approved these changes

2024-05-26 20:44 UTC, merged