chore: remove search clue component and its logic
devhatt/octopost pull request #474
Opened 2024-04-18 18:20 UTC by JpBurgarelli

Closes #466 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Essa task tinha com objetivo remover o componen SearchClue.
Basicamente, nesta Task, apenas removi o searchClue, suas importações e lógicas derivadas do sideBar onde era importado e fiz a covarage chegar a 100%.

Porém, acabei tendo que remover também uma função/botão implementado pelo Zoldyck no sideBar, pois o ele estava ali, única e exclusivamente, para que, quando esse botão fosse clicado, as estilizações que ele fez para o sideBar na versão mobile fossem aplicadas/chamadas. Então, acabava se tornando inútil, porque ele colou isso ali apenas para ele ver e acabaram aprovando sem pedir para ele remover.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

https://github.com/devhatt/octopost/assets/30197026/b946a27a-3f72-48c4-bef7-a9771104f849

https://github.com/devhatt/octopost/assets/30197026/c160f236-d758-4b11-9ff9-32f4f47acbfe

</details>

2024-04-18 21:02 UTC, zoldyzdk requested changes

2024-04-18 21:02 UTC, zoldyzdk commented on src/pages/home/components/Sidebar/Sidebar.tsx
>              ref={inputSearchRef}
o inputSearchRef era usado pelo SearchClue, é necessário manter ele??

2024-04-21 14:05 UTC, JpBurgarelli commented on src/pages/home/components/Sidebar/Sidebar.tsx
>              ref={inputSearchRef}
Ele é usado pelo inputSarch também.

2024-04-21 14:06 UTC, JpBurgarelli commented on src/pages/home/components/Sidebar/Sidebar.tsx
> -            onChange={(data) => setValue(data as string)}
Não, mas, para remover o searchClue, é preciso remover o estado "value"  e, também, essa prop do inputSearch, já que ela utiliza o setValue.

2024-04-21 14:10 UTC, zoldyzdk submitted a review, later dismissed

2024-04-21 15:29 UTC, alvarogfn commented
![image](https://github.com/devhatt/octopost/assets/62889807/de0489ba-f846-4118-bf0f-ce06b3e1ef09)

bota 100% de coverage pra nois

2024-04-24 02:06 UTC, Alecell requested changes
Faltou apagar o componente em si

2024-04-25 18:02 UTC, JpBurgarelli commented
Basicamente, nesta Task, apenas removi o searchClue, suas importações e lógicas derivadas do sideBar onde era importado e fiz a covarage chegar a 100%. 

Porém, acabei tendo que remover também uma função/botão implementado pelo Zoldyck no sideBar, pois o ele estava ali, única e exclusivamente, para que, quando esse botão fosse clicado, as estilizações que ele fez para o sideBar na versão mobile fossem aplicadas/chamadas. Então, acabava se tornando inútil, porque ele colou isso ali apenas para ele ver e acabaram aprovando sem pedir para ele remover.

2024-04-25 18:09 UTC, zoldyzdk approved these changes

2024-04-25 18:46 UTC, merged