Update README.md
devhatt/octopost pull request #485
Opened 2024-04-22 15:42 UTC by GabrielTrindadeC

Closes #484 

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- [x] **Banner do projeto**: Adicionado banner do projeto ao README.
- [x] **Índice**: Adicionado índice ao README.
- [x] **Introdução do projeto**: Adicionada introdução do projeto ao README.
- [x] **Explicação do projeto**: Adicionada explicação do projeto ao README.
- [x] **Como contribuir**: Adicionado guia de como contribuir ao README.
- [x] **Como rodar o projeto**: Adicionado guia de como rodar o projeto ao README.
- [x] **Tirar dúvidas**: Adicionada seção de como tirar dúvidas ao README.
- [x] **Regras**: Adicionadas regras ao README.
- [x] **Redes sociais**: Adicionada seção de redes sociais ao README.
- [x] **Texto**: Algumas informações de uso geral foram movidas para o README da org, ex: cargos
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked

</details>

2024-04-22 16:08 UTC, aalmeida00 submitted a review, later dismissed

2024-04-24 02:38 UTC, Alecell requested changes
O link do node não ta funcionando

O link do discord não ta funcionando

Coloca na imagem do layout o link pro figma tambem, alem disso coloca o link antes da imagem

nas extensoes coloca o link para as extensoes no vscode store

na parte de duvidas menciona que as duvidas devem ser tiradas no chat do projeto em questao e inclusive linka para o chat

Cita tambem os 1x1 que temos

Cita tambem as dailies

Sobre o como contribuir, linka pra tela de issues do octopost sendo que esse é do octopost e nao fala "projetos" fala especificamente do octopost (precisamos do template)

porque o link de flow issues ta num commit em especifico do octo? Nao poderia ser um projeto de "readme" onde lá teria todos os reads da devhatt? Cria ai pra nois 
Mesma coisa pras diretrizes de contribuição

O styleguide deve ser especifico por projeto! Isso ta tudo bem, mas precisamos desse styleguide no projeto no commit master do octo

2024-04-24 20:11 UTC, GabrielTrindadeC commented
> O link do node não ta funcionando
> 
> O link do discord não ta funcionando
> 
> Coloca na imagem do layout o link pro figma tambem, alem disso coloca o link antes da imagem
> 
> nas extensoes coloca o link para as extensoes no vscode store
> 
> na parte de duvidas menciona que as duvidas devem ser tiradas no chat do projeto em questao e inclusive linka para o chat
> 
> Cita tambem os 1x1 que temos
> 
> Cita tambem as dailies
> 
> Sobre o como contribuir, linka pra tela de issues do octopost sendo que esse é do octopost e nao fala "projetos" fala especificamente do octopost (precisamos do template)
> 
> porque o link de flow issues ta num commit em especifico do octo? Nao poderia ser um projeto de "readme" onde lá teria todos os reads da devhatt? Cria ai pra nois Mesma coisa pras diretrizes de contribuição
> 
> O styleguide deve ser especifico por projeto! Isso ta tudo bem, mas precisamos desse styleguide no projeto no commit master do octo

2024-04-24 20:15 UTC, GabrielTrindadeC commented
> O link do node não ta funcionando
- aqui funciona normalmente
> O link do discord não ta funcionando
- resolvido
> Coloca na imagem do layout o link pro figma tambem, alem disso coloca o link antes da imagem
- resolvido
> nas extensoes coloca o link para as extensoes no vscode store
- resolvido
> na parte de duvidas menciona que as duvidas devem ser tiradas no chat do projeto em questao e inclusive linka para o chat
- resolvido
> Cita tambem os 1x1 que temos
- resolvido
> Cita tambem as dailies
- resolvido
> Sobre o como contribuir, linka pra tela de issues do octopost sendo que esse é do octopost e nao fala "projetos" fala especificamente do octopost (precisamos do template)
- resolvido e adiconado link
> porque o link de flow issues ta num commit em especifico do octo? Nao poderia ser um projeto de "readme" onde lá teria todos os reads da devhatt? Cria ai pra nois Mesma coisa pras diretrizes de contribuição
- provavelmente foi interface troll
> O styleguide deve ser especifico por projeto! Isso ta tudo bem, mas precisamos desse styleguide no projeto no commit master do octo
- provavelmente foi interface troll

2024-04-24 21:06 UTC, aalmeida00 approved these changes

2024-04-30 01:06 UTC, merged