feat: feedback error mobile
devhatt/octopost pull request #490
Opened 2024-04-24 22:35 UTC by thiagoCalazans-dev

Closes #489

<details open> 
  <summary>
    <b>Feature</b>

  </summary>

Criação de componente para mensagem de erro no mobile.

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual reference</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/98334306/8489d392-85e9-4f85-b15e-abbe03dcc57d)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-25 18:07 UTC, zoldyzdk requested changes

2024-04-25 18:07 UTC, zoldyzdk commented on src/components/FeedbackError/FeedbackError.tsx
> +  const [showErrors, setShowErrors] = useState(true);
Olha essa mudança do state inicial faz com que o component já apareça com o ErrorDropdown ativo, não sei se esse era a ideia inicial pra o FeedbackError

2024-05-01 13:16 UTC, Alecell requested changes
Seu PR foi criado em cima do PR do JP? Se não precisamos verificar o porque seu PR tem muito mais arquivo do que deveria ter. Basicamente aqui existem alterações que não são do seu componente, me confirma se veio do JP, se não veio, fale com o @PiluVitu pra saber oque fazer. As coisas que me fazem pensar isso é: Toda a remoção do SearchClue, o teste e o componente Sidebar, alteração do tipo InputSearch

Falando de organização, dentro do componente `FeedbackError` vamos ter uma pasta chamada `components` e dentro dessa pasta vamos ter o componente `FeedbackErrorMobile` a fim de seguir a arquitetura atual do projeto

2024-05-01 13:16 UTC, Alecell commented on src/components/FeedbackError/mobile/FeedbackErrorMobile.stories.tsx
> +
Remover linha em branco

2024-05-01 13:16 UTC, Alecell commented on src/components/FeedbackError/mobile/FeedbackErrorMobile.type.ts
> +};
Esse formato dessa interface deve derivar da interface de erro que temos. Falar com JP

2024-05-01 13:16 UTC, Alecell commented on src/components/FeedbackError/mobile/FeedbackErrorMobile.tsx
Seu componente está certo, mas acredito que precisamos conversar um pouco sobre a escalabilidade dele. Me chame assim que possivel para discutirmos sobre, cola no plantão!

2024-05-08 00:48 UTC, Alecell requested changes
Apenas alguns comentários bem simples!!

2024-05-08 00:48 UTC, Alecell commented on src/components/FeedbackError/components/FeedbackErrorMobile.module.scss
> +  }
Tem 100% de ctz que cada uma das propriedades aqui são necessárias?

Aparentemente tem algumas coisas aqui que não são necessárias!

2024-05-08 00:48 UTC, Alecell commented on src/components/FeedbackError/components/FeedbackErrorMobile.stories.tsx
Muito bom!

2024-05-08 00:48 UTC, Alecell commented on src/components/FeedbackError/components/FeedbackErrorMobile.module.scss
> +.errorContainer {
Isso precisa de um `cursor: pointer`

2024-05-08 00:48 UTC, Alecell commented on src/components/FeedbackError/components/FeedbackErrorMobile.tsx
> +  return Object.entries(errors).length > 0 && renderErrorMobile();
Tenta usar o `isEmpty` ao inves do object entries

2024-05-08 13:37 UTC, thiagoCalazans-dev commented on src/components/FeedbackError/components/FeedbackErrorMobile.module.scss
> +  }
removi os que percebi que já eram globais

2024-05-09 11:15 UTC, zoldyzdk approved these changes

2024-05-12 16:36 UTC, Alecell requested changes

2024-05-12 16:36 UTC, Alecell commented on src/components/FeedbackError/components/FeedbackErrorMobile.tsx
> +  return !isEmpty(Object.entries(errors)) && renderErrorMobile();
Não não, o `isEmpty` é justamente pra evitar o uso do `Object.entries`, no caso fica assim
```suggestion
  return !isEmpty(errors) && renderErrorMobile();
```

2024-05-15 00:29 UTC, Alecell approved these changes

2024-05-15 10:54 UTC, zoldyzdk approved these changes

2024-05-15 10:55 UTC, merged