Issue 472 - Main Content
devhatt/octopost pull request #501
Opened 2024-05-02 14:02 UTC by DominMFD

Closes #472 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Foi criado funções para tratar o limite de texto e de algumas propriedades de mídia

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/134434652/6231a1d6-4382-4afc-acb1-e9f66cd62518)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

## Funções Principais

Todas as funções criadas fazem a validação de algumas propriedades de mídia e texto, conforme informado na issue #472, devemos fazer esse tratamento no front e essas funções auxiliam isso.

### Texto

Para o texto temos a função `validateTextLength()` que verifica a quantidade de caracteres do texto.

### Mídia

Para a mídia temos a função `validateMediaSize()` que verifica o tamanho da mídia, seja ela imagem ou vídeo.

###  Imagem

Para a imagem temos 2 funções: 

- `validateImageResolution()` verifica a  resolução da imagem;
- `validateImageAspectRatio()` verifica o aspect ratio da imagem.

### Vídeo 

Para vídeo temos 2 funções: 

- `validateVideoResolution()` verifica a  resolução do vídeo;
- `validateVideoDuration()` verifica a duração do vídeo.

## Funções auxiliares

Foi criado 2 funções auxiliares para pegar as dimensões da imagem e do vídeo, são elas `getImageDimensionsFromFile()` e `getVideoDimensionsAndDurationFromFile()`. Elas retornam as propriedades do File para auxiliar nas validações.

</details>

2024-05-06 17:30 UTC, hxsggsz approved these changes

2024-05-06 17:30 UTC, hxsggsz commented
ta bala, falta resolver conflito no eslint

2024-05-06 21:29 UTC, zoldyzdk approved these changes

2024-05-06 22:15 UTC, Alecell requested changes
Cada uma das funcionalidades idealmente deveria estar em outro arquivo na minha visão, pelo menos não colocar tudo num `index.ts`, talvez colocar um arquivo pra cada tipo de validador, tipo **media** e _text_ ja seria bem maneiro

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.spec.ts
> +});
O seu describe pode ser um grande `describe` que dentro tem dentro as validações expecificas tipo

```js
describe('Validate', () => {
  describe('input text', () => {
     it('max lenght', () => {})
  })
})
```

lembre-se que seus `describe`s e `it`s, devem conversar na hora do output do teste para ficar legivel e intendivel

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.spec.ts
> +    }));
Po, isso ta muito ruim de ler, bobear tacar isso num outro arquivo de mock, talvez numa pasta de mocks mesmo onde vc define isso tudo que ta acontecendo aqui de forma abstraida seria o ideal

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.spec.ts
> +    ).rejects.toThrow('File is not a image');
To throw? Acho que não, isso não é um erro.

Um erro é quando algo acontece dentro do nosso app que não esperamos e não temos caso de tratamento, isso é um erro. Nesse caso é apenas um check fail pq o arquivo é muito grande, vc precisa retornar algo como `false` ou coisa parecida

Talvez o nome do método poderia ser `isImageResolutionValid()` ou `checkImageResolution()` ou algo assim, retornando apenas um `true` ou `false` de se é valido ou nao.

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.spec.ts
> +      });
Mesma coisa aqui, colocar esse mock numa pasta de mocks de forma reutilizavel e talz, desse jeito aqui ta muito ruim de ler

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.spec.ts
> +    ).rejects.toThrow('File is not a video');
Aqui a mesma coisa, não é throws

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.ts
Esse pattern de chamar os métodos de `validate` eu nao gosto muito, não que seja totalmente errado, mas sei la, algo não me cheira bem

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.ts
> +
Apaga essa linha em branco

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/index.ts
> +  return imageAspectRatio <= limitAspectRatio;
Isso aqui ta verificando mesmo o aspect ratio? Se eu mandar um 16x9 por exemplo funciona? Acho que não, que tipo de `number` que precisar ter no `limitAspectRatio`?

Acho que precisa repensar essa questão do AR

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/mediaDimensions.ts
> +export async function getImageDimensionsFromFile(
Acho esse nome meio exagerado...

Talvez um `getFileDimensions` seria bem legal, até pq ai eu poderia usar esse mesmo método pra vídeo e pra imagens, ai dentro dele vc chama oque precisa chamar, oque acha?

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/mediaDimensions.ts
> +}
Seguindo a mesma linha eu não concordo com um método que dimensions e duration, pq não um método que seja `getVideoData`? Ai vc pode retornar um objeto que tem duration, AR e mais coisas conforme a necessidade, acho que seria mais interessante de usar algo assim

2024-05-06 22:15 UTC, Alecell commented on src/utils/validadeMediaAndText/mediaDimensions.types.ts
> +export type TVideoDimensions = {
Não estamos mais usando o padrão de `T`, `I` e coisas do genero, pode remover e usar o tipo sem o prefixo

2024-05-12 16:46 UTC, Alecell requested changes
Essa organização de arquivos ta bem esquisita pra mim, coisas que parece que deveriam estar juntas estào separadas, coisas que deveriam ta separadas tao juntas, precisamos rever isso.

2024-05-12 16:46 UTC, Alecell commented on src/utils/validateMediaAndText/mocks/mockFiles.ts
BOM

2024-05-12 16:46 UTC, Alecell commented on src/utils/validateMediaAndText/mocks/mockLoadImage.ts
> +}
isso ta erradinho... O mock tem q ser agnostico, no caso esse é um pouco chumbado, um mock deve poder ser usado assim como a instancia original, nesse caso vc vai chamar `mockLoackImage`, mas precisa ser um `imageMock` onde tem no caso alguns dos métodos do `Image`

2024-05-12 16:46 UTC, Alecell commented on src/utils/validateMediaAndText/mocks/mockLoadVideo.ts
mesma coisa do image

2024-05-12 16:46 UTC, Alecell commented on src/utils/validateMediaAndText/validadeText/validadeText.spec.ts
> +  it('validate text length', () => {
Seu `describe` e `it` devem conversar, ou seja, quando o teste rodar precisamos ler algo como `Text validation limit text length` sendo `describe('Text validation'` e `it('limit text length'`

2024-05-12 16:46 UTC, Alecell commented on src/utils/validateMediaAndText/validateMedia/utils/getMediaData.ts
pq o `getAspectRatio` fica fora do `getMediaData`?

2024-05-12 16:46 UTC, Alecell commented on src/utils/validateMediaAndText/validateMedia/validateImage/validateImage.spec.ts
> +  it('validate image aspect ratio', async () => {
mesma coisa aqui sobre a descricào dos testes

2024-05-14 12:25 UTC, Alecell reviewed
Precisamos conversar

2024-05-14 15:00 UTC, hxsggsz submitted a review, later dismissed
pra mim ta muito bom, só senti falta de você ser um pouco mais descritivo nos its e describes dos seus testes

2024-05-14 15:04 UTC, hxsggsz commented
e dar um nome melhor pra esse pr tambem, o titulo ta dizendo uma coisa mas você ta fazendo outra

2024-05-29 16:29 UTC, Alecell requested changes

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/MediaInput.tsx
> +      const mediaErrors = await validatorFile(file);
mudar os nomes dos metodos pra imperativo, no caso `validate`

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/MediaInput.tsx
> +    <div className={scss.manyMediaContainer} data-testid="manyMediaInputs">
Esse testid idealmente deveria ser removido se possivel e fazer a query por outra coisa na pag

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/mediaValidator.spec.ts
> +  });
Mesma coisa, colocar casos de falha

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/mediaValidator.spec.ts
> +describe('check medias', () => {
Isso aqui tem q ser o nome da classe, os testes não podem estar juntos assim no mesmo it, nesse caso vc nem tem q ter essas duas versoes, manda apenas um validator, nesse momento vc nao ta testando a diferença entre eles. Vc vai ter 2 validators quando vc for testar duração de uma media por exemplo, (que nao tem aqui vale dizer precisa por) tem q dar erro se tentar checar a duração de uma imagem e coisas assim

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/videoValidator/videoValidator.spec.ts
Ta faltando teste aqui, seus testes devem cobrir os casos mais usuais do componente, eles não estào fazendo isso.

2024-05-29 16:29 UTC, Alecell commented on src/i18n/index.ts
> +void use(initReactI18next).init({
Q? porque?

2024-05-29 16:29 UTC, Alecell commented on src/mocks/mockMedias/mockFiles.ts
> +const _10_MB_FILE = 1;
Não inicie com `_`

2024-05-29 16:29 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +  const currentPostMode = socialMedias
Declaração de variaveis devem acontecer no inicio do arquivo

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/interfaces/fileValidator.ts
Pq apenas esse cara foi parar dentro de um `interfaces` sem um `.types`? Ele não poderia ser o `.types` do `mediaValitors.ts`?

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/mediaValidators.ts
> +    this.media.aspectRatio(limitAspectRatio);
Se ambas as funções de `aspectRatio` são iguais não tem sentido separar em outra função, reusar dentro das classes pra usar aqui, bastaria que esse método aqui fizesse o trabalho.

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/utils/getAspectRatio.ts
Acho que esse arquivo vai de ralo

2024-05-29 16:29 UTC, Alecell commented on src/components/MainComposer/components/MediaInputs/utils/mediaValidator/videoValidator/videoValidator.ts
> +    console.log(height, width);
Remover `console.log`

2024-06-13 15:38 UTC, Alecell approved these changes

2024-06-13 16:59 UTC, Alecell approved these changes

2024-06-13 16:59 UTC, merged