Issue 259  patch 1
devhatt/octopost pull request #517
Opened 2024-05-22 16:07 UTC by thiagoCalazans-dev

Closes #259

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

adjust conflicts from PR: https://github.com/devhatt/octopost/pull/410

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-24 12:37 UTC, Alecell requested changes
Sei q tu pegou o bonde andando, mas temos alguns problemas aqui

2024-05-24 12:45 UTC, Alecell requested changes

2024-05-24 12:45 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.ts
> +} as const;
Importar resoluções do SCSS se for possivel. Renomear as propriedades do objetos pra `from[res]`, tipo `from1240`, `from905` e etc

2024-05-24 12:45 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.ts
> +// Reference: src/styles/breakpoints.scss
Apagar comentário

2024-05-24 12:45 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.ts
> + */
Remover comentário

2024-05-24 12:45 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.spec.ts
Esse arquivo precisa ser inteiramente revisto

2024-06-06 19:26 UTC, Alecell commented on src/styles/breakpoints.module.scss
EOF

2024-06-06 19:26 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.spec.ts
> +  const queryValue = query.match(/\d+/g) as RegExpMatchArray; // converts (min-width: 600px) to ['600']
Remover comentários

2024-06-06 19:26 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.spec.ts
> +    // Simulate a screen with width greater than sm
Remover comentário

2024-06-06 19:26 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.spec.ts
> +    // Simulate a screen with width greater than sm
Remover comentário

2024-06-06 19:55 UTC, thiagoCalazans-dev commented on src/styles/breakpoints.module.scss
o que é EOF ?  kkkk

2024-06-06 20:38 UTC, Alecell requested changes

2024-06-08 01:39 UTC, Alecell requested changes

2024-06-08 01:39 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.ts
> +console.log('VARIABLES ====>', variables);
Remover console.log

2024-06-08 01:39 UTC, Alecell commented on src/hooks/useMediaQuery/useMediaQuery.ts
> +import variables from '../../styles/breakpoints.module.scss';
usar path alias

2024-06-10 17:05 UTC, Alecell approved these changes

2024-06-10 17:47 UTC, juliaam commented
Precisa atualizar a branch, remover os conflitos

2024-06-10 18:32 UTC, juliaam commented
A sua branch está dando erro no tabber e não está sendo possível testar

2024-06-10 18:58 UTC, juliaam commented
O problema é muito grande, a branch é muita antiga e está conflitando com muitas coisas no projeto, devido a isso, a pull request será fechada.

2024-06-10 18:58 UTC, juliaam commented
O problema é muito grande, a branch é muita antiga e está conflitando com muitas coisas no projeto, devido a isso, a pull request será fechada.

2024-06-10 18:58 UTC, closed without merging