refactor the test for the use of roles
devhatt/octopost pull request #522
Opened 2024-06-04 20:48 UTC by wendesongomes

Closes #506  

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Essa task tinha como objetivo em alterar o test que antes era com `className` e agora o test passou a ser com `getByRole`. Nesse PR fiz somente a alteração do test. 

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/82889172/69854d6c-d538-4fe7-82d1-aea35887709e)

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
- [X] Tests created
</details>

</details>

2024-06-05 11:00 UTC, Alecell requested changes
Só uma pequena alteração!!!

2024-06-05 11:00 UTC, Alecell commented on src/components/CharacterLimitMainText/components/CharacterLimit.tsx
> +    <div className={svgColor} role="alert">
Isso aqui não é um alert, acredito que não devemos pegar o elemento pela `role`, mas sim pelo texto

2024-06-05 11:00 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimitMainText.spec.tsx
> +    const optionElements = screen.getAllByRole('alert');
Sabendo que o componente `CharacterLimitMainText` renderiza limites de caracteres usando numeros podemos provavelmente fazer a busca por numeros, algo como `getByText(/\d/)`, alias acredito que aqui é melhor buscar por text do que por role!

2024-06-05 18:25 UTC, hxsggsz approved these changes

2024-06-06 13:37 UTC, Alecell approved these changes

2024-06-06 14:14 UTC, merged