Issue 465 - Filtro do inputsearch
devhatt/octopost pull request #523
Opened 2024-06-05 14:53 UTC by juliaam

Closes #465 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

</details>

<details open> 

- **Description**
Adicionada o comportamento de filtragem no input search do sidebar

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/35346206/0da0e911-5ab9-453b-8363-5605d4fc459a)
![image](https://github.com/devhatt/octopost/assets/35346206/4325ddfd-dd8c-4f5f-ad62-494778281946)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

2024-06-05 15:14 UTC, Alecell requested changes

2024-06-05 15:14 UTC, Alecell commented on package.json
> +    "@types/lodash.debounce": "4.0.9",
isso tem q ser dev dependency

2024-06-05 15:14 UTC, Alecell commented on src/setupTests.ts
> +import '@testing-library/jest-dom';
Verifica se seus testes ainda passam removendo essa linha pf

2024-06-05 15:14 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.spec.tsx
>  // TODO: revisitar esse teste pois está falhando
Apagar o TODO, ou o teste ainda está falhando?

2024-06-05 15:14 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.spec.tsx
> +  it('renders accounts correctly', async () => {
acho que aqui podemos ser mais especificos, `renders all accounts from store`

2024-06-05 15:14 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.spec.tsx
> +  it('renders when accounts is empty correctly', () => {
no caso aqui, `dont renders accounts when accounts store is empty`

Na sua descrição precisa explicar o motivo de ser correctly, correclty em si não tem significado, por siso precisamos deixar claro oq o teste é

2024-06-05 15:14 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.spec.tsx
Vamos colocar os testes do filtro dentro de um outro `describe` e precisamos ter alguns testes como:
- Busca por conta
- Busca por nome de acordion (isso funciona/deveria funcionar?)
- Busca por uma conta que nao existe, oq acontece? Precisamos testar

Vamos cobrir os casos de teste mais basicos do componente separando com o `describe`

2024-06-05 17:45 UTC, DominMFD approved these changes

2024-06-07 12:05 UTC, Alecell requested changes

2024-06-07 12:05 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +      : filteredAccounts;
Oi? Alo? Q? Why?

2024-06-07 12:05 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.spec.tsx
> +});
A ideia era que esse `describe` ficasse dentro do outro lá

2024-06-07 12:05 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +          )}
POG, gosto, mas precisamos ter um teste pra isso tambem se formos ter esse recurso, acho tambem melhor colocar tudo isso numa função

```tsx
renderNoResultsFound()
```

2024-06-09 01:49 UTC, Alecell approved these changes

2024-06-09 01:49 UTC, merged