Active post modes
devhatt/octopost pull request #560
Opened 2024-06-18 17:13 UTC by Luiginicoletti

Pull Request
Closes #502  

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
Nesse PR criamos o componente define uma store global para gerenciar o estado das contas de redes sociais utilizando a biblioteca **Zustand.** 

Ele permite **adicionar** e **remover** contas, mantendo a lista de contas atualizada de forma reativa.

### Funcionalidades Principais:
**Definição de Tipos:**

**AccountPost:** Tipo que representa uma conta simplificada, contendo apenas os campos **id**, **socialMediaId** e **userName**.
**StoreState**: Tipo que define a estrutura da store, incluindo uma lista de contas e funções para **adicionar** e **remover** contas.

**Criação da Store:**

A store é criada usando a função create do **Zustand**, que inicializa um estado com uma lista de contas vazia e define as funções para manipulação desse estado.

**Funções da Store:**

**addAccount**: Adiciona uma nova conta à lista de contas.
 Cada conta é representada por seu **id**, **socialMediaId** e **userName**.
**removeAccount**: Remove uma conta da lista de contas com base no id da conta.

</details>
<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

Alteramos a lógica de preenchimento das abas de redes sociais no componente **Tabber**, que antes utilizava uma mock-API, para consumir dados de um estado global gerenciado com **Zustand**. Corrigimos várias incompatibilidades e garantimos que as abas refletem corretamente o estado dos switches das contas de redes sociais na sidebar.

Precisamos corrigir algumas incompatibilidades para a migracao da fonte dos dados:
As incompatibilidades surgiram devido à transição do uso de uma mock-API para um estado global.
Antes, as contas eram carregadas e exibidas diretamente a partir de dados mockados, sem integração real com os switches na sidebar. 

- Substituímos a fonte de dados mockada por um estado global com Zustand, que agora reflete o estado dos switches.
- Implementamos verificações de tipo para garantir que as funções de manipulação de estados recebam e tratem corretamente os dados.
- Adicionamos lógica para garantir que a última aba seja removida corretamente quando a última conta de rede social for desativada.
- Corrigimos a inicialização de estados para prevenir erros de tipos e garantir uma transição suave quando os dados mudam.

</details>
<details> 
  <summary>
    <b>Changelog</b>
  </summary>
- Substituição da lógica de preenchimento de abas de redes sociais do componente `Tabber` para consumir dados do estado global gerenciado pelo Zustand.
- Correção de incompatibilidades de tipo entre `AccountPost` e `Account`.
- Adição de verificações de segurança para assegurar a correta manipulação de estados e dados.
- Implementação de lógica para remover a última aba corretamente ao desativar a última conta.
</details>
<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

<img width="886" alt="Screenshot 2024-06-18 at 14 11 29" src="https://github.com/devhatt/octopost/assets/17785028/ef571bbf-5d3a-44c5-9607-79fe4596eeb5">

<img width="999" alt="Screenshot 2024-06-18 at 14 12 25" src="https://github.com/devhatt/octopost/assets/17785028/bac69029-e8da-4bb4-814a-19c4bba2c6bc">

</details>
<details open> 
  <summary>
    <b>Checklist</b>
  </summary>
 Issue linked
 Build working correctly
 Tests created
</details>
<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Estado Global: O Zustand agora gerencia o estado das contas de redes sociais ativas, refletindo diretamente os switches na sidebar.
Verificação de Tipos: Melhoramos a verificação de tipos em várias partes do código para garantir que os dados são manipulados corretamente.
Melhorias na Interface: As abas agora reagem dinamicamente às mudanças nos switches, proporcionando uma melhor experiência do usuário e uma interface mais consistente.
</details>

2024-06-18 19:10 UTC, juliaam requested changes

2024-06-18 19:10 UTC, juliaam commented on src/components/Tabber/utils.ts
> +  ) {
```suggestion
  if (socialMedia.postModes.length === 0
  ) {
```
São necessárias todas essas validações? tente assim, você testando se tem length no postmodes já resolve

2024-06-18 19:18 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +
Po, não acho necessário, acho que um if else é super legível, mas se fizer questão posso alterar.

2024-06-18 19:20 UTC, Luiginicoletti commented on src/components/Tabber/utils.ts
> +  ) {
Estava testando só o básico mas temos muitas regras de lint etc... que estavam causando problemas, esta foi a solução que encontrei.

2024-06-18 19:22 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +
Bom de qualquer forma vou alterar.

2024-06-19 13:09 UTC, DominMFD approved these changes
Amassou Nico, parabéns!!!

2024-06-19 13:10 UTC, DominMFD approved these changes
Amassou Nico, parabéns!!!

2024-06-19 13:31 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +
corrigido!

2024-06-19 13:31 UTC, Luiginicoletti commented on src/components/Tabber/Tabber.tsx
feito!

2024-06-19 14:37 UTC, juliaam requested changes

2024-06-19 14:37 UTC, juliaam commented on src/components/Tabber/Tabber.tsx
> +      setCurrentTab(initialTabId as TabId);
Se há o if para cair no initialTabId, o accounts.length > 0 vai ser sempre true, não há necessidade de fazer a mesma verificação dentro do if
```suggestion
    if (accounts.length > 0) {
      const initialTabId = makeId(accounts[0]);
      setCurrentTab(initialTabId);
```

2024-06-19 14:37 UTC, juliaam commented on src/components/Tabber/Tabber.tsx
> +      setCurrentTab('' as unknown as TabId);
Necessário esse unknown? Por que?
```suggestion
      setCurrentTab('' as TabId);
```

2024-06-19 14:37 UTC, juliaam commented on src/components/Tabber/Tabber.tsx
> +  }, [accounts, socialMedias]);
O socialMedias precisa ficar nas dependências do useEffect? O tab não tem que ser setado apenas quando accounts mudar, que é na troca do activateSocialTab?

2024-06-19 14:37 UTC, juliaam commented on src/components/Tabber/Tabber.tsx
> +            postMode={currentPostMode ?? undefined}
Aqui já vai ser retornado PostMode ou undefined
```suggestion
            postMode={currentPostMode}
```

2024-06-19 14:37 UTC, juliaam commented on src/components/Tabber/Tabber.tsx
> +              ''
Seria desejável colocar `tabs[currentTab].posts[tabs[currentTab].postModeOnView]?.text ??` em uma variável e trocar os locais onde é chamada, seria uma sugestão, algo como: 
```suggestion
              postModeOnViewText ?? ''
```
(reveja o nome da variável)

2024-06-19 14:37 UTC, juliaam commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +
Corrija os problemas de code-style. Com a atualização da branch, o id se tornou number, necessário que seja alterado e verificado em todos os locais que você utilizou. 
Outro ponto, é que caso não dê pra usar o ternário por erro de lint, sem problemas voltar para o if else

2024-06-19 14:37 UTC, juliaam commented on src/stores/useAccountStore.ts
> +import { StoreAccount } from './useSocialMediaStore.types';
Corrija o import 
```suggestion
import { StoreAccount } from '~stores/useSocialMediaStore/useSocialMediaStore.types';
```

2024-06-19 14:37 UTC, juliaam commented on src/stores/useAccountStore.ts
> +  removeAccount: (accountId: string): void => {
```suggestion
  removeAccount: (accountId: number): void => {
```

2024-06-19 14:37 UTC, juliaam commented on src/stores/useAccountStore.ts
> +  removeAccount: (accountId: string) => void;
```suggestion
  removeAccount: (accountId: number) => void;
```

2024-06-19 14:40 UTC, juliaam commented
Precisa corrigir os problemas das actions

2024-06-19 16:05 UTC, Alecell approved these changes

2024-06-19 16:06 UTC, merged