Issue 551 - Add scroll to side bar
devhatt/octopost pull request #563
Opened 2024-06-19 15:27 UTC by Tassio-Med

Closes #551 

<details open> 
  <summary>
    <b>Implementado scroll lateral quando o Accordions de contas ultrapassa o tamanho da Sidebar</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

2024-06-20 18:37 UTC, juliaam requested changes

2024-06-20 18:37 UTC, juliaam commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +  height: 100%;
remove o height duplicado, já tem um acima
```suggestion

```

2024-06-20 18:37 UTC, juliaam commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +          {/* {isEmptyResult ? renderEmptyResult() : renderSearchData()} */}
remove o comentário
```suggestion
```
```suggestion
          <div className={scss.scrollableContent}>
            {isEmptyResult ? renderEmptyResult() : renderSearchData()}
          </div>
```

2024-06-20 18:37 UTC, juliaam commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +  padding: 0 5px;
Utilize a unidade rem para padding e margin e para elementos relativos

Nesse caso 0.5rem = 5px

```suggestion
  padding: 0 0.5rem;
```

caso queira saber um pouco melhor sobre quais unidades utilizar e onde: https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/

2024-06-20 18:37 UTC, juliaam commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +    margin-left: 3px;
Nesse caso também utilizar rem 
```suggestion
    margin-left: 0.3rem;
```

2024-06-20 18:37 UTC, juliaam commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +    width: 4px;
```suggestion
    width: 0.4rem;
```

2024-06-20 18:37 UTC, juliaam commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +
O layout do scroll tem um problema, não dá pra visualizar aonde a barra que scrolla está 
![image](https://github.com/devhatt/octopost/assets/35346206/8a327b58-850b-498f-8630-266adc0a2288)

2024-06-21 15:09 UTC, Tassio-Med commented
Olá,

Os erros abaixo foram corrigidos:

**Arquivo Sidebar.tsx**
✅ Comentário desnecessário removido.

**Arquivo Sidebar.module.scss**
✅ Substuído `px` por `rem`.
✅ Removido `height` duplicado da classe `.content`.
✅ Cores ajustadas para melhor visualização da barra de scroll.

As mudanças estão prontas para serem revisadas.
Obrigado!

2024-06-21 15:23 UTC, Alecell requested changes

2024-06-21 15:23 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +  max-height: 80vh;
Seu container precisa esticar até o maximo que consegue e então fazer o scroll acontecer, algo derivado dos outros tamanhos que temos na pag, o `max-height` é basicamente uma `height` fixa e vamos evitar isso!

2024-06-21 15:23 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +  }
POG DEMAIS

2024-06-21 15:48 UTC, Tassio-Med commented
Os erro abaixo foi corrigido:

**Arquivo Sidebar.module.scss**
✅ Removido `max-height: 80vh`.

Tudo pronto para ser revisado.

2024-06-24 18:01 UTC, juliaam requested changes

2024-06-25 15:08 UTC, Tassio-Med commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +  flex-direction: column;
Gente, desculpa.
Era linha de código de teste que eu tava usando enquanto resolvia a task. Pura falta de atenção minha.

2024-06-25 15:12 UTC, Tassio-Med commented
O erro abaixo foi corrigido:

Arquivo Sidebar.module.scss
✅ Removido `flex-direction: column`.

Eu tinha usado como teste no código e acabei esquecendo de remover. 😅

Código pronto para ser revisado.
Obrigado!

2024-06-25 17:25 UTC, juliaam approved these changes

2024-06-29 13:13 UTC, Alecell requested changes

2024-06-29 13:13 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.module.scss
Ainda não está correto o comportamento!

Acho que pode ser uma boa conversarmos sobre, acho que não to conseguindo explicar certinho como deveria ser!

2024-07-15 13:57 UTC, Alecell commented
@Tassio-Med seu pr tava aqui na minha lista, mas ainda ta errado, me pinga em algum momento pra vermos isso. O container não pode ter tamanho limite fixo em px ou tela, mas sim no tamanho do seu grid

2024-08-06 03:13 UTC, closed without merging