Mobile home structure/#533
devhatt/octopost pull request #566
Opened 2024-06-21 21:00 UTC by JpBurgarelli

Closes #533 

  <summary>
    <b>Feature</b>
  </summary>

A task consiste em ajustar a tela inicial do layout princiapal, como a disposicao dos componentes fica na versao mobile. Isso envolve ocultar os módulos que não são necessários na versão móvel e criar a estrutura básica da página para facilitar a adição dos demais componentes conforme necessário. Como se poder ver,  nas esta igual, pois falta o desenvolvimento do layout.

  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

Layout:
![image](https://github.com/devhatt/octopost/assets/30197026/ba0196cb-0511-495b-af97-9004dc7821be)

Minhas mudancas:
![image](https://github.com/devhatt/octopost/assets/30197026/0fa25824-0370-4fa6-a905-4139c01a4207)

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
</details>

2024-06-22 20:02 UTC, JpBurgarelli commented
Ajustei as bordas de divisoes:
![image](https://github.com/devhatt/octopost/assets/30197026/3b7f9a61-56d8-4594-af61-4f353f624bf0)

2024-06-22 20:03 UTC, JpBurgarelli commented
Como esta versao desktop ( acima de 905px ):
![image](https://github.com/devhatt/octopost/assets/30197026/b4c760fe-6b95-475f-ad55-2fcaba2f202b)

2024-06-24 17:48 UTC, juliaam commented
O visual de desktop foi alterado para um que difere do figma, dê uma checada nisso


Como está:
![image](https://github.com/devhatt/octopost/assets/35346206/4e97ffa3-8c62-41e4-b661-7e406984e675)

Como estava e deveria ficar:
![image](https://github.com/devhatt/octopost/assets/35346206/df96f827-e032-427e-aee7-5e35c6596d4a)

O modal aberto também está com problemas no menor tamanho, mas seria importante checar pra ver se isso engloba a sua task com o ale:

![image](https://github.com/devhatt/octopost/assets/35346206/c30307e7-c5a7-4369-818f-00655ea18fba)

2024-06-24 17:50 UTC, juliaam requested changes
O visual de desktop foi alterado para um que difere do figma, dê uma checada nisso


Como está:
![image](https://github.com/devhatt/octopost/assets/35346206/b91bcafe-3050-4b02-861f-0c44229d3892)



Como estava e deveria ficar:
![image](https://github.com/devhatt/octopost/assets/35346206/4e97ffa3-8c62-41e4-b661-7e406984e675)

O modal aberto também está com problemas no menor tamanho, mas seria importante checar pra ver se isso engloba a sua task com o ale:

![image](https://github.com/devhatt/octopost/assets/35346206/c30307e7-c5a7-4369-818f-00655ea18fba)

2024-06-25 16:16 UTC, JpBurgarelli commented
Obsevacao feita pela julia corrigida:

![image](https://github.com/devhatt/octopost/assets/30197026/b3b66f63-d3ce-40f5-b055-955df6533b96)

2024-06-25 17:44 UTC, juliaam requested changes
Como está:
![image](https://github.com/devhatt/octopost/assets/35346206/3650a382-5c5a-4f02-8084-2993e383ce54)

Como deveria ficar:

![image](https://github.com/devhatt/octopost/assets/35346206/697d1dde-6ed9-4868-ba30-39667a1532f1)

Consegue arrumar essa div? o padding e o tamanho do botão parece não estar de acordo com o figma

2024-06-25 17:45 UTC, juliaam commented
Falta atualizar a branch também!

2024-06-26 19:32 UTC, JpBurgarelli commented
ajustei o padding e tamanho do button

![image](https://github.com/devhatt/octopost/assets/30197026/692e1cea-1ed8-4a37-9de2-e61b64410e33)

2024-07-01 13:37 UTC, Alecell requested changes

2024-07-02 17:12 UTC, JpBurgarelli commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +                + New Account
feito!

![image](https://github.com/devhatt/octopost/assets/30197026/41a02fa6-e51f-4e06-be1d-b175b205383e)

2024-07-02 17:48 UTC, JpBurgarelli commented
As regiões do ajuste que fiz mantiveram a consistência do teste. Print para evidenciar que o que não foi testado não pertence à minha task.

![image](https://github.com/devhatt/octopost/assets/30197026/0a969538-f80c-4a8a-9319-5bf5df49ed57)

![image](https://github.com/devhatt/octopost/assets/30197026/ddb22a15-06a4-447e-9afb-4414a992c4f6)

2024-07-02 22:14 UTC, juliaam approved these changes
muito bom jp 😁

2024-07-08 13:24 UTC, aalmeida00 approved these changes

2024-07-10 17:11 UTC, merged