Character limit no MainComposer do Tabber
devhatt/octopost pull request #570
Opened 2024-06-29 16:04 UTC by zoldyzdk

Closes #557 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Character limit exibindo o limite de cada postmode de cada rede social separadamente ao invés do total como é feito no MainComposer.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>

[CharacterLimit.webm](https://github.com/devhatt/octopost/assets/90076846/eae188c3-b90d-4aa3-aad5-1b9ce84d5eee)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-07-01 17:37 UTC, Alecell requested changes

2024-07-01 17:37 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +  return null;
Conversamos

2024-07-01 22:39 UTC, Alecell approved these changes

2024-07-01 22:42 UTC, Alecell requested changes
Só está faltando uma coisa, no limite de caracteres que aparece no tabber **não** deve aparecer os limites das outras redes na esquerda 
![image](https://github.com/devhatt/octopost/assets/13935760/918632b3-9d3b-433b-b6cb-64a31c0c4183)

2024-07-12 18:22 UTC, juliaam requested changes
Precisa atualizar a branch, e não está com o comportamento esperado.

![image](https://github.com/user-attachments/assets/6d945f82-a1d0-4edc-afa6-c8cf216dbbb9)

2024-07-15 19:37 UTC, juliaam approved these changes

2024-07-16 11:51 UTC, Alecell approved these changes

2024-07-16 11:51 UTC, merged