Ajuste no useError e emissão dos errors de mídia e texto.
devhatt/octopost pull request #573
Opened 2024-07-11 17:14 UTC by DominMFD

Closes #528 #565 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

 Fiz um pequeno ajuste no componente useError e criei a comunicação de erros entre os componentes ComposerEditor e MediaInputComposer com o MainComposer para ele colocar ou remover os erros no useError.

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
 No componente `useError` fiz uma pequena alteração na nomenclatura do método de adicionar um erro, antes estava `setError`, agora esta `addError`, a modificação também foi feita no types do componente. Outra modificação no `useError` é que agora ele só recebe uma mensagem e o id é sempre gerado pelo nanoId, antes ele podia receber um Id também.

 Agora o componente `MainComposer` é responsável pela comunicação entre os errors do `ComposerEditor` e `MediaInputComposer`  e o `useError`, adicionando e removendo os Erros. O `MainComposer` sempre recebe informações dos erros do `ComposerEditor` e do `MediaInputComposer`, se teve erro ou não.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

2024-07-12 20:14 UTC, juliaam requested changes
Tem um comportamento que não é esperado, o mesmo erro está sendo adicionado várias vezes na listagem de erros, isso resulta em quando se não há mais aquele erro em específico, somente o último erro é removido, as cópias antigas deles ainda permanecem exibindo

Note que na imagem, mesmo tendo apenas 10 caracteres, ainda tem muitos erros sendo exibidos, isso porque eu passei várias vezes do limite de caracteres, e todos eles foram se adicionando, aí quando eu removo, somente o último é removido
![image](https://github.com/user-attachments/assets/b54955b1-e156-4c0a-837c-b6950b16e008)

2024-07-15 15:03 UTC, Alecell commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +  const errorRemover = (id: string | undefined): void => {
Nao era number?

2024-07-15 15:05 UTC, Alecell commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +  const handleErrors = (id: string, error: Error): void => {
Aqui não era pra ser `set` ou algo do genero? `handle` passa uma sensação genérica, mas ele não é generico

2024-07-15 15:06 UTC, Alecell commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +    if (message) {
Pq temos essa verificação? O objeto não vai ter mensagem sempre?

2024-07-15 15:08 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.type.ts
> +export type MediaErrorMap = Record<MEDIA_ERRORS | number, string>;
Mesma coisa do outro

2024-07-15 15:08 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.type.ts
> +  removeError?: (id: string | undefined) => void;
Pq `undefined`?

2024-07-15 15:09 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +import { Action } from '../MainComposerBase/MainComposerBase.type';
Não precisamos da action agora que iremos usar o else

2024-07-15 15:17 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +    if (props.onChange) props.onChange(event);
Acho que gosto do `?.` sera que nao vale usar?

2024-07-15 15:17 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
>      }
Acho que tinhamos conversado de pensar num jeito melhor de escrever isso, não?

2024-07-15 16:50 UTC, DominMFD commented on src/components/FeedbackError/FeedbackError.tsx
> +          <li key={error.message}>{error.message}</li>
Pq o id do error foi removido

2024-07-15 16:50 UTC, DominMFD commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.type.ts
> +}
é verdade, da pra tirar

2024-07-15 16:55 UTC, DominMFD commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.types.ts
> +  removeError?: (id: string | undefined) => void;
Então, quando eu tava fazendo ele deu algum erro que poderia ser undefined, mas agora q eu tirei não deu não.

2024-07-15 19:29 UTC, DominMFD commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +    if (message) {
vai sim, eu só esqueci de tirar mesmo.

2024-07-15 19:37 UTC, DominMFD commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
>      }
esse foi o jeito melhor 😭, vou melhorar ainda mais

2024-07-25 15:03 UTC, juliaam requested changes
revisei oq consegui, mas reparei um erro de funcionamento no ladle

2024-07-25 15:04 UTC, juliaam commented
https://github.com/user-attachments/assets/e3b7f304-d707-474e-b94e-7d4e0ff108d1

2024-08-07 13:12 UTC, PiluVitu approved these changes

2024-08-09 18:48 UTC, Alecell requested changes

2024-08-13 13:58 UTC, juliaam requested changes

2024-08-13 13:58 UTC, juliaam commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +  const renderImputMediaGroup = (): ReactNode => {
```suggestion
  const renderInputMediaGroup = (): ReactNode => {
```

2024-08-13 13:58 UTC, juliaam commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +        {props.postMode ? renderImputMediaGroup() : <InputMediaGroup />}
isso acabou não ficando claro, se props.postMode for verdadeiro, ele renderiza InputMediaGroup, se não, ele renderiza o componente InputMediaGroup. Parece a mesma coisa

2024-08-22 12:58 UTC, Alecell requested changes
Existem interfaces que fazem sentido semantido de derivarem de algo maior e apenas implementar suas peculiaridades entre o InputMediaGroup e o ComposerEditor? Se tiver é bom fazer esse reuso

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
>      }
Não precisamos desse spread antes pq usamos o `error` apenas para uma verificação
```suggestion
    const errorId = nanoid();
    const error = errors[textErrors];

    if (!error) {
      setErrors({ ...errors, [textErrors]: errorId });
      props.addError?.(errorId, errorForAdd);
    }
```

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +  const [errors, setErrors] = useState<TextErrorMap>();
Iniciar com um obj vazio

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +    setErrors(newErrors as TextErrorMap);
Qual a diferença do `newError` e do `newErrors`?

```suggestion
    const errorId = errors [textErrors];
    const newErrors = omit(errors, [textErrors]);

    if (errorId) props.removeError?.(errorId);

    setErrors(newErrors);
```

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
Prefira a nomenclatura `nextErrors` a `newErrors`

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.type.ts
> +  removeError?: (id: string) => void;
Acredito que esse tipo e o tipo do ComposerEditor poderiam implementar a mesma interface escopada, mas aplicando suas especificidades

```
interface PensarNumNome {
  accountId?: string;
  addError?: MainComposerErrorEmiter;
  removeError?: (id: string) => void;
  postMode?: PostMode;
}

interface MediaInput extends PensarNumNome { }
interface ComposerEditorProps extends PensarNumNome {
  currentMaxLimit?: number;
  onChange?: InputChange;
  value?: string;
}
```

2024-08-22 12:58 UTC, Alecell commented on src/components/Preview/Preview.module.scss
Essa não é a soluçào

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +    if (props.postMode) removeErrors(id);
Coloca essa função no if de baixo antes do `for`

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +  const updateMedia = async (
preciso saber pra que serve, se ainda faz sentido e se precisa de refactor as coisas que ja estavam nessa função uma vez que mudamos tanta coisa

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
>    const setMedias = (medias: Media[]): void => {
Espaço entre bloco de função e declaração de variavel

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
>    const medias = mainContent.medias ?? [];
Declaraçào de variavel deve ir pro inicio do bloc

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +      const fileValidator = Object.values(fileValidators({ media, validator }));
`validators` pq são varios validadores. O mesmo vale pro text

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +      for (const validators of fileValidator) {
`validator`

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +    const validator = props.postMode?.validators.media;
`validatorRules`

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +        setErrors({ ...errors, [file.id]: fileErrors });
Sempre abrir blocos de ifs complexo

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
> +      if (Object.keys(fileErrors).length > 0)
```suggestion
      if (!isEmpty(fileErrors))
```

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
Tanto pro componente de texto quanto o de media possa ser legal ter uma variavel que faz tipo isso

`const hasValidation = Boolean(props.postMode)`

Substituindo o if do props.postMode pq essa condicional não diz muito sobre oq ela significa

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/InputMediaGroup.tsx
>      setMedias(list);
mesma coisa do `addMedia`, ele precisa de tudo q tem aqui?

Vale dizer, pode ser legal usar algo diferente de `findIndex`

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/InputMediaGroup/utils/fileValidator/fileValidator.ts
Aplicar o ajuste proposto no text

2024-08-22 12:58 UTC, Alecell commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +          renderInputMediaGroupWithProps()
Aplicar o novo styleguide

2024-08-22 20:12 UTC, Alecell requested changes

2024-08-22 20:12 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
>      const newValue = event.target.value;
```suggestion
    const { value } = event.target;
```

2024-08-30 14:07 UTC, Luiginicoletti approved these changes

2024-08-30 17:51 UTC, juliaam requested changes

2024-08-30 17:51 UTC, juliaam commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +  const hasValidation = Boolean(props.postMode);
esse nome ficou um pouco confuso, não deveria ser hasPostMode ou algo do tipo?

2024-08-30 17:51 UTC, juliaam commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.type.ts
> +  postModeId: string | undefined;
pode undefined?

2024-08-30 17:51 UTC, juliaam commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.type.ts
> +  accountId: string | undefined;
pode undefined?

2024-08-30 17:51 UTC, juliaam commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +        {props.postMode && 'media' in props.postMode.validators ? (
coloca dentro de uma variável que deixe claro oq é

2024-09-02 16:10 UTC, JpBurgarelli approved these changes

2024-09-02 16:10 UTC, JpBurgarelli commented
att a branch aeww!

2024-09-05 14:58 UTC, juliaam approved these changes
LGTM, ficou mt bom domingas, parabéns

2024-09-05 15:02 UTC, merged