chore: add correct icon & adjust name
devhatt/octopost pull request #574
Opened 2024-07-11 17:20 UTC by JpBurgarelli

Closes #533 

  <summary>
    <b>Feature</b>
  </summary>

A tarefa consiste em ajustar a seta do socialAccordion para manter a consistência do layout, pois, antes, tínhamos dois tipos de setas diferentes, conforme retrata a imagem abaixo.

Eu também fiz uma mudança no nome da "seta" para baixo. No projeto, temos ícones que são, de fato, setas, e temos triângulos que lembram setas, porém são triângulos e, em algum momento, poderia acabar havendo uma confusão do ponto de vista semântico. Portanto, em vez de chamar dropDownArrow, agora chama-se TriangleDropArrow (dando a entender que é uma seta para baixo, mas em formato de triângulo).

  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

Layout:

Como esta:
![image](https://github.com/devhatt/octopost/assets/30197026/284c1ea6-746b-4c44-a971-f4a91a85a625)
![image](https://github.com/devhatt/octopost/assets/30197026/ef803fbe-8ba4-4ef1-b12c-6f958727519b)

Como estava:
![image](https://github.com/devhatt/octopost/assets/30197026/e6b07b70-f9fa-43cf-86a4-cbc4bc7ba2be)

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
</details>

2024-07-12 16:23 UTC, juliaam approved these changes

2024-07-16 12:03 UTC, Alecell approved these changes

2024-07-16 12:03 UTC, Alecell commented on src/components/Icon/data.ts
> +  TriangleLeftArrow: TriangleLeftArrow,
O icone precisa seguir o padrão de nomenclatura dos outros, inclusive aproveita e refatora os que estão com `camelCase` pra `quebab-case`

O problema não é a parte da direita, mas a da esquerda, precisa ser assim
```js
"triangle-left-arrow": TriangleLeftArrow
```

É legal aproveitar e ajustar o nome dos outros que estão fora de padrão

2024-07-16 12:06 UTC, Alecell requested changes
aprovei sem querer

2024-07-18 11:49 UTC, Alecell approved these changes

2024-07-18 11:49 UTC, merged