issue-470 - favoritar contas
devhatt/octopost pull request #575
Opened 2024-07-18 19:22 UTC by juliaam

Closes #470 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adicionar funcionalidade de favoritar as contas de redes sociais

<details open> 
  <summary>
    <b>Visual evidences:
![image](https://github.com/user-attachments/assets/2c14af52-c920-4c23-98fa-c038e053d9a2)

</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

2024-07-23 12:15 UTC, Alecell requested changes

2024-07-23 12:15 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +          }}
OI? Crime!

CRIME

CRIME 🚓🚓🚓🚓🚓🚓🚓🚓🚓🚓🚨🚨🚨🚨🚨🚨🚨🚨

NUNCA de async no meio de um componente, se o seu componente ta precisando dar algum await ele ta perdendo na assincronidade q um componente precisa ter.

Nào coloque função inline tambem, a menos q elea seja apenas uma chamada simples, se vc precisa abrir o bloco o negócio já fica BEM ruim de ler

Pq mudamos o paramtro  `favorite` pra `isFavorited`? Não era melhor manter?

Porque temos uma chamada inline pra chamar uma função que já existe no nosso componente? Acho que se só arrancar o `async/await` inclusive já fica deboas pra colocar numa linha só
```suggestion
          onFavoriteChange={(favorite) => favoriteAccount(favorite, account)}
```

2024-07-23 12:15 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +  };
Essa funçào a mesma coisa, não precisa de async aqui, o componente vai ser atualizado de forma async e tudo bem, não precisamos aguardar nada aqui!

Se o problema é lint vc pode usar 
```suggestion
  const favoriteAccount = (
    isFavorited: boolean,
    account: StoreAccount
  ): void => {
    void updateAccount({ ...account, favorite: isFavorited });
  };
```

2024-07-23 12:15 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +  const socialMediaName = socialMedias.get(props.socialMediaId)?.name;
Ai esse name viria por props

2024-07-23 12:15 UTC, Alecell commented on src/stores/useSocialMediaStore/useSocialMediaStore.types.ts
> +    data: StoreAccount[];
Pq removeu o estado `null`? Ele é importante pra diferenciarmos um estado vazio (a pessoa não tem contas) de quando a request nunca nem aconteceu 🤔

2024-07-23 12:15 UTC, Alecell commented on src/stores/useSocialMediaStore/useSocialMediaStore.ts
> +    AccountsService.update(account),
Entendo o pq vc fez como fez, provavelmente pq de limitações do json-server, mas não é legal mandar a entidade inteira pra fazer um update, oq temos que mandar é o id da conta e se ela vai ser favoritada ou não.

Inclusive deveria ser um método apenas de favoritar, da forma como ta basicamente a entidade conta ta na nossa mão oq é sad

2024-07-23 12:15 UTC, Alecell commented on src/stores/useSocialMediaStore/useSocialMediaStore.ts
> +    data: [],
Aqui é o role do `null` q comentei no tipo

2024-07-23 12:15 UTC, Alecell commented on src/services/api/accounts/accounts.ts
> +  },
Deveria ser apenas um `favorite`

2024-07-23 12:15 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +  isFavoriteAccordion?: boolean;
Não gosto dessa prop `isFavoriteAccordion` tira versatilidade e escalabilidade do componente, se formos ter outros formatos vamos colocar esses outros `is` tambem? A solução aqui é ter uma `prop` de `name` ou `title` pq ai o componente, independente de quantas variações ele tenha, sempre vai funcionar com pouca ou até (provavelmente) nenhuma alteração do componente em si.

2024-07-23 12:15 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +      />
Acho que tomamos um gap logico aqui.

Seu accordion de favorites tinha que estar na lista de contas, não? Pelo menos na lista de favorited?

Não sei se é legal filtrar isso sempre que atualizar, temos um dado meio dificil de lidar e tratar, acredito que tudo que for favoritado tinha que já estar em um accordion proprio ja no objeto que tem as contas

2024-07-23 12:15 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +  }, [accounts.data]);
Real não gosto disso de colocar useMemo em tudo sem ter problema de performance, entendo que é uma forma de programação defensiva, mas vamos falar isso no papo do style guide hoje então safe

2024-08-01 10:19 UTC, DominMFD reviewed
Só notei um probleminha, ta dando erro no request da API, da uma olhada por favor 
![image](https://github.com/user-attachments/assets/c86eea7e-6134-46da-85fa-5641d7a1caba)

2024-08-02 17:10 UTC, juliaam commented
@PiluVitu

2024-08-05 12:06 UTC, PiluVitu approved these changes

2024-08-06 18:40 UTC, JpBurgarelli requested changes

2024-08-06 18:40 UTC, JpBurgarelli commented on src/pages/home/components/Sidebar/Sidebar.spec.tsx
> +    const favoriteAccordion = screen.getByText('Contas favoritas');
Nossos codigos sao em Inglês.

2024-08-06 18:40 UTC, JpBurgarelli commented on src/pages/home/components/Sidebar/Sidebar.components.tsx
> +        title="Contas favoritas"
Nossos codigos sao em Inglês.

2024-08-08 11:08 UTC, DominMFD approved these changes

2024-08-09 19:06 UTC, Alecell requested changes

2024-08-09 19:06 UTC, Alecell commented on src/stores/useSocialMediaStore/useSocialMediaStore.ts
Role que conversamos

```
const accounts = {
  data: {
     favorite: {
        asuidygasuy: {},
        ausydgasuydas: {} 
     },
     facebook: {
        uytasgfdfatsyda: {},
        asiudhaysud: {}
     }
  }    
}
```

2024-08-15 20:55 UTC, juliaam commented on src/stores/useSocialMediaStore/useSocialMediaStore.types.ts
> +  ) => Promise<Account | undefined>;
pq se cair no catch (error) ele retorna undefined pois n tem return

2024-08-27 05:27 UTC, Luiginicoletti approved these changes

2024-08-30 10:18 UTC, Alecell requested changes
O problema da estrela sumida foi resolvido?

2024-08-30 10:18 UTC, Alecell commented on src/components/AccountCard/AccountCard.tsx
>        <p className={scss.username}>{username}</p>
`span`

2024-08-30 10:18 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.components.tsx
> +  });
Dor em, porque mesmo que isso é necessário? isso deveria acontecer no hook, não?

2024-08-30 10:18 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.components.tsx
> +            title={socialMedias.get(socialMediaId)?.name as string}
Esse as não deveria ser necessário, se é tem algo errado

2024-08-30 10:18 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +  icon?: ReactElement;
O icone é condicional? Pq?

2024-08-30 10:18 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
Pq o as string é necessário?

2024-08-30 10:18 UTC, Alecell commented on src/stores/useSocialMediaStore/useSocialMediaStore.ts
> +  },
Isso não ta grande demais pra só atualizar uma conta que era de X lugar e agora vai pra Y lugar/

2024-08-30 18:27 UTC, juliaam commented on src/components/AccountCard/AccountCard.tsx
>        <p className={scss.username}>{username}</p>
no entendo

2024-09-06 21:44 UTC, JpBurgarelli approved these changes

2024-09-09 11:49 UTC, Frompaje commented on mock-api.json
```js
"avatar": "https://example.com/image1.jpg"
```
Não é melhor botar o nome das imagem, tipo assim?

```js
"avatar": "https://example.com/image-discord.jpg"
```
Caso eu precise em outro componente, não vou ficar na duvida sobre o que é a imagem2

2024-09-09 11:53 UTC, juliaam commented on mock-api.json
tem uma task pra ajustar esses ícones manito

2024-09-11 10:57 UTC, DominMFD approved these changes

2024-09-12 17:16 UTC, devlefel approved these changes
amei como o botao foi pintado =D

2024-09-16 17:07 UTC, DominMFD approved these changes

2024-09-16 17:08 UTC, merged