Issue 545 - Colocar Icones no componente de limite de caracteres
devhatt/octopost pull request #578
Opened 2024-07-20 05:15 UTC by gustavogularte

Closes #545 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adicionei os ícones facebook, discord, twitter, tiktok, instagram no componente characterLimit

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
No figma não tinha o ícone do discord, mas como o discord é usado de exemplo em várias partes tive que adicionar ele tbm ao mock-api e adicionar o icon dele. Também tive que fazer algumas alterações no typescript e em teste mudando o que o props.svg recebe de ReactNode para IconsType.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/user-attachments/assets/fa636715-be62-4894-a6ab-d09d60ecb78f)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

2024-07-22 18:00 UTC, juliaam requested changes
Com as alterações, está dando erro em alguns locais, e não é possível iniciar o projeto por conta disso
Você precisa alterar nos locais que usam os icons que você alterou para que seja adequado ao modo que você deixou agora e não tenha mais erros, inclusive nos testes, dá uma checada geral
![image](https://github.com/user-attachments/assets/fe378902-9df0-45b3-8c25-6938fc38ee3b)
![image](https://github.com/user-attachments/assets/c813c6e3-c7ba-477b-8068-8cb53926203f)

2024-07-22 18:00 UTC, juliaam commented on src/components/CharacterLimitMainText/CharacterLimit.spec.tsx
> +    render(<CharacterLimit maxLength={10} svg={'discord'} value="1234" />);
```suggestion
    render(<CharacterLimit maxLength={10} svg="discord' value="1234" />);
```
Se você só vai passar string, não é preciso que passe entre {}

2024-07-22 18:00 UTC, juliaam commented on src/components/CharacterLimitMainText/CharacterLimit.tsx
> +        {props.svg ? <Icon icon={props.svg} size={24} /> : null}
Se você quer que apareça o icon apenas quando tiver props.svg, você pode fazer dessa forma
```suggestion
        {props.svg && <Icon icon={props.svg} size={24} />}
```

2024-07-22 18:00 UTC, juliaam commented on src/components/CharacterLimitMainText/CharacterLimit.types.ts
> +  svg: IconsType | null | undefined;
por que undefined também? 
```suggestion
  svg: IconsType | null ;
```

2024-07-22 22:10 UTC, gustavogularte commented on src/components/CharacterLimitMainText/CharacterLimit.types.ts
> +  svg: IconsType | null | undefined;
é que la no composerEditor acho que o socialMedias poderia ser undefined, aí eu adicionei que svg pode ser undefined e null

2024-07-23 13:25 UTC, Alecell requested changes

2024-07-26 17:23 UTC, JpBurgarelli approved these changes

2024-07-29 21:02 UTC, juliaam approved these changes
muito bom 😄

2024-07-29 21:02 UTC, juliaam commented
atualiza a branch

2024-07-31 12:51 UTC, Alecell requested changes

2024-07-31 12:51 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +                icon={socialMedias.get(postMode.socialMediaId)?.icon ?? null}
pq `?? null`?

2024-07-31 12:51 UTC, Alecell commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +          icon={null}
pq o icone pode ser null?

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.types.ts
> +  icon: IconsType | null;
Preciso saber pq o icone pode ser `null`

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.tsx
> +  return props.icon ? renderWithIcon() : renderWithoutIcon();
Coloca no nosso formato novo baseado no styleguide

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.spec.tsx
Para os testes vamos sempre descreve-los com imperatividade tipo `it('renders...`, quando usamos `render` não ta imperativo, quando usamos `renders` ta no imperativo, a mesma coisa do `apply`, ficaria no caso `applies`

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.spec.tsx
>    });
nesse teste vc pode testar se renderiza o `max-length` tambem, nao precisamos de 2 testes de render

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.spec.tsx
>    });
Esse teste pode ser apagado

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.spec.tsx
>    });
Esse teste precisa ser baseado num `userEvent` ou numa alteração de `props` do componente

2024-07-31 12:51 UTC, Alecell commented on src/components/CharacterLimitMainText/CharacterLimit.spec.tsx
>    });
Não é seguro testarmos coisas baseado em `class`, precisamos usar outras informações pra saber se excedeu ou não. Existe alguma outra informação desse tipo?

2024-08-02 21:41 UTC, Luiginicoletti commented
Aparentemente o computador dele pifou, qualquer coisa se não conseguir dar continuidade até segunda feira, podemos pausar essa PR, e liberar a issue para que outras pessoas peguem.

2024-08-06 03:12 UTC, closed without merging