Issue 546 - Adicionar ícone de erro no accordion
devhatt/octopost pull request #584
Opened 2024-08-12 18:18 UTC by jorge933

Closes #546 

<details open> 
  <summary>
    <b>Feature</b>
   <p>A tarefa consiste em exibir um ícone de erro de acordo com o campo <code>valid</code> e indicar qual conta está com erro.</p>
  </summary>

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
    <br>
    <img src="https://github.com/user-attachments/assets/fdec503a-c986-4a66-8bf9-86a1a9e18b06">
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
</details>

2024-08-12 22:48 UTC, aalmeida00 approved these changes

2024-08-12 22:56 UTC, aalmeida00 commented
Só queboru uns testes @jorge933 

![image](https://github.com/user-attachments/assets/aea8a946-9256-4577-ac0c-25170efc097c)

2024-08-13 11:30 UTC, DominMFD approved these changes

2024-08-13 18:53 UTC, juliaam requested changes
Então, tá com um erro no layout de como deve ficar no fim. Está sendo exibido o número de contas mesmo quando há erro um erro nas contas, isso não está de acordo com o layout. Deve haver o número de contas, ou o erro de que há alguma conta inválida:

Layout
![image](https://github.com/user-attachments/assets/3ffed1f5-b4fe-424a-909f-256ad0007550)

Seu PR:
![image](https://github.com/user-attachments/assets/3a565372-391f-4b44-82d7-e05ae3212b14)

2024-08-14 14:14 UTC, juliaam approved these changes
muito bom! 😀

2024-08-14 14:18 UTC, juliaam commented
acho que seria legal colocar todos os valores como valid: true, pra quando chegar na master ficar mais agradável

2024-08-15 01:35 UTC, Alecell requested changes

2024-08-15 01:35 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +              {props.accounts.some(({ valid }) => !valid) ? (
oq isso faz exatamente? Verifica se temos alguma conta valida? Acho que seria uma boa colocar essa chamada de função numa variavel e usar a variavel

2024-08-15 01:35 UTC, Alecell commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +};
Não sei se entendi pq precisamos disso, consegue me explicar?

2024-08-16 14:20 UTC, jorge933 commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.type.ts
> +};
são as propriedades de um component que a Julia mandou eu criar
![image](https://github.com/user-attachments/assets/9b58a255-d070-475b-aa58-1ada3eafc8bd)

2024-08-16 20:09 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +                <Icon className={scss.alertIcon} icon={'alert'} size={16} />
```suggestion
                <Icon className={scss.alertIcon} icon="alert" size={16} />
```

2024-08-16 20:10 UTC, aalmeida00 approved these changes
Vale ajustar esse pequeno pontinho, de resto tá legit.

2024-08-19 19:36 UTC, merged