Refactor tabber
devhatt/octopost pull request #588
Opened 2024-08-15 14:05 UTC by DominMFD

Closes #582 

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

Nessa task fizemos o refactor store de Post, que antes estava como `useAccountPost`, agora passa a ser `usePostStore` com métodos novos e consistentes.  Com a mudança da store, tivemos que refatorar o componente `Tabber` e seus filhos, para a melhora do fluxo de informações, mais facilidade de buscar informações e maior consistência e escalabilidade, principalmente no `Tabber`.

Também houve uma pequena mudança na estrutura de pastas do projeto, A pasta do componente `Tabber` agora se encontra na pasta componentes da pasta home que está localizado na pasta pages `(pages/home/components)` e não na pasta components do src, onde se encontra a maioria dos componentes. Essa mudança foi feita pois o componente `Tabber` é um componente direto da home da aplicação, o que melhora na arquitetura do projeto.

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

O que fazer com Testinho?

</details>

2024-08-16 20:06 UTC, aalmeida00 commented on src/pages/home/components/Tabber/Tabber.tsx
> +export default Tabber;
faltou eof, vale olhar teu linter xisde

2024-08-29 17:33 UTC, Luiginicoletti requested changes

2024-08-29 17:33 UTC, Luiginicoletti commented on mock-api.json
> +          "postModeId": "DISCORD__POST_POSTMODE_ID",
```suggestion
          "postModeId": "DISCORD_POST_POSTMODE_ID",
```

2024-08-29 17:33 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.tsx
> +    if (!enabled && actualPost) remove(actualPost.id);
Isso ficou bonito!

2024-08-30 18:09 UTC, juliaam commented
precisa remover a store de useaccount

2024-09-04 18:16 UTC, Luiginicoletti approved these changes

2024-09-04 20:22 UTC, JpBurgarelli approved these changes

2024-09-05 19:33 UTC, Alecell requested changes

2024-09-05 19:33 UTC, Alecell commented on src/pages/home/components/Tabber/Tabber.tsx
> +      )}
Sei não em

Se o sync deriva de um postmode pois oq pode ou não estar sync é o postmode, porque o isSync ta aqui? Ta estranho

2024-09-05 19:33 UTC, Alecell commented on src/pages/home/components/Tabber/Tabs/Tabs.tsx
> +  const findAccount = (tab: Tab): FoundAccount =>
`foundAccount` ou mesmo `account`

2024-09-05 19:33 UTC, Alecell commented on src/pages/home/components/Tabber/Tabs/Tabs.tsx
> +        {Object.entries(props.tabs).map(([, tab]) => renderTabs(tab))}
Era legal colocar no formato do style guide

2024-09-09 17:42 UTC, DominMFD commented on src/stores/usePostStore/usePostStore.spec.ts
> +/* eslint-disable unicorn/no-unused-properties */
Porque tava dando erro eslint nas propriedades que não estavam sendo usadas

2024-09-09 17:44 UTC, juliaam commented on src/pages/home/components/Tabber/Tabber.tsx
> +/* eslint-disable unicorn/prefer-at -- using at is not better than using .length - 1 */
sim, os dois, o primeiro é pra fazer os ifs necessários e o segundo é pq o .length tá sendo bem melhor do que usar at

2024-09-09 17:50 UTC, juliaam commented on src/pages/home/components/Tabber/Tabs/Tabs.types.ts
> +export type FoundAccount = StoreAccount | null | undefined;
Isso é o tipo de retorno de uma função, o FoundAccount faz um find de accounts.data, que pode ser null ou StoreAccount[]. Ou seja, os três tipos são necessários, o undefined do método find e o null do storeaccount junto com o proprio storeaccount

2024-09-09 17:56 UTC, juliaam commented on src/components/MainComposer/components/MainComposerBase/MainComposerBase.tsx
> +        maxCharacters={props.maxCharacters ?? undefined}
pq no ComposerEditor o maxCharacters não é obrigatório, visto que ele é utilizado no CharacterLimit, porém há casos em que ele usa o maxLimit quando não tem maxCharacters, então não tem oq fazer, só se a gente passasse props.maxCharacters ?? null, que eu acho que seria um modo melhor, mas pode ser desnecessário

![image](https://github.com/user-attachments/assets/a607bf28-69b1-48a2-a35a-3d8b9215b253)

2024-09-09 18:10 UTC, juliaam commented on src/components/MainComposer/components/ComposerEditor/ComposerEditor.tsx
> +      const validators = postModes?.validators as TextValidator;
o que?

2024-09-21 02:29 UTC, PiluVitu approved these changes
LGTM

2024-09-25 13:29 UTC, merged