fix: post mode identifier
devhatt/octopost pull request #601
Opened 2024-08-22 15:47 UTC by gustavogularte

Closes #543 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

 implementado a funcionalidade e o layout do componente que permite selecionar o modo/tipo de post que desejam publicar em determinada rede.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/user-attachments/assets/3ce86048-3379-43d0-87a1-5f46d27084b3)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

2024-08-23 02:34 UTC, juliaam requested changes

2024-08-23 02:34 UTC, juliaam commented on src/components/Tabber/PostModes/PostModes.tsx
> +    new Set()
não vejo a necessidade de criar um set, ele é criado para evitar repitações, no entanto, nesse caso não vai se repetir. Então, não é necessário essa complexidade a mais pra esse caso

2024-08-26 14:33 UTC, DominMFD reviewed
só tem um probleminha, o post mode que será postado continua marcado para todas as contas. Por exemplo, se vc marcar o reels em uma conta, ele vai ser marcado em todas as contas ativas.

https://github.com/user-attachments/assets/6a595646-dfd6-4b7d-baaf-54fa5d875a06

2024-08-28 14:17 UTC, DominMFD requested changes

2024-08-28 14:17 UTC, DominMFD commented on src/components/Tabber/PostModes/PostModes.tsx
> +    Record<string, string[] | undefined>
Cria um type pra esse Record

2024-08-29 11:17 UTC, DominMFD approved these changes

2024-08-29 14:03 UTC, aalmeida00 requested changes

2024-08-29 14:03 UTC, aalmeida00 commented on src/components/Tabber/PostModes/PostModes.module.scss
> +  background-color: #f8f2f7;
Essa cor nao tá no global? vale colocar

2024-08-29 17:12 UTC, Luiginicoletti approved these changes

2024-08-29 18:14 UTC, JpBurgarelli requested changes
bala demais!
Da um espaçamento para a área de texto so.

![image](https://github.com/user-attachments/assets/7f6af6c3-4227-4675-837e-d028f224a1b1)

2024-08-30 10:50 UTC, Alecell requested changes
Mano seu CSS ta MUITO bom, de verdade, simples e funcional, tudo que precisava ser!!

Sobre layouting uma alteraçào que **eu sei** que é diferente do figma. Coloca a borda do checkbox com roxinho tbm! 
![image](https://github.com/user-attachments/assets/c51b0997-b57a-4b9a-8ed7-400c11fcb008)

Preciso só que adicione o componente no `ladle` e tambem faça os testes do componente!

Um ultimo pedido, seu componente precisa continuar funcionando quando entramos em situaçòes de responsividade

Isso pode ser resolvido com scroll lateral e fade no seu componente igual a @juliaam fez no componente de tabber. 
![image](https://github.com/user-attachments/assets/e4c30851-c14e-4e05-9c8c-962fea9326e1)

2024-08-30 10:50 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +  };
Ow isso aqui q eu fiz ficou uma merda em asudiygasfyusa

FUnciona, mas é redundante, pode só retornar o `Boolean(selectedPostModes[currentTab]?.includes(postModeId));` e alegria

2024-08-30 10:50 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +    }
```suggestion
    if (isChecked) setSelectedPostModes(addPostMode(postModeId));
    else setSelectedPostModes(removePostMode(postModeId));
```

2024-08-30 10:50 UTC, Alecell commented on src/components/Tabber/PostModes/PostModes.tsx
> +      className={`${scss.selectPostMode} ${postModeClasses(postMode.id)}`}
Idealmente colocar isso numa variavel e usa-la ou coisa semelhante, abrir template string em prop é smell

2024-09-04 20:31 UTC, JpBurgarelli reviewed
att a branch ae, meu mano Arend!

2024-09-18 21:43 UTC, juliaam requested changes
consegue ajustar isso que se vc adicionar varios postmodes ele expande o container principal? seria interessante q tivesse so o teu scroll mesmo e ele nao se expandisse
![image](https://github.com/user-attachments/assets/bea2f277-f747-4700-b87c-c4010170d207)

2024-09-18 21:43 UTC, juliaam commented on src/components/Tabber/PostModes/PostModes.spec.tsx
> +    }
isso pode tirar em testes, nao pode jogar erro assim. acho q vc fez por conta de eslint, mas pode tirar

2024-09-18 21:43 UTC, juliaam commented on src/components/Tabber/PostModes/PostModes.spec.tsx
> +      }
isso pode tirar em testes, nao pode jogar erro assim

2024-09-18 21:43 UTC, juliaam commented on src/components/Tabber/PostModes/PostModes.tsx
> +        {socialMedia?.postModes.map(renderPostMode)}
coloca no novo formato do styleguide, ao invés de vc passar uma function, passe como um componente. Crie um PostModes.components.tsx e coloque esse postmode lá, pode seguir o exemplo do sidebar.components, se tiver duvida, me chama

2024-09-27 20:33 UTC, juliaam requested changes
ficou muito bom, o resultado com o scroll ficou mt interessante, só o design que está diferente do figma, é só esse ajuste

![image](https://github.com/user-attachments/assets/de58d2cf-8557-49b4-b7b6-f7b59f52e158)


figma:

![image](https://github.com/user-attachments/assets/7f1a4267-d84f-4d4e-a1b1-7a548a944719)

2024-09-28 15:14 UTC, juliaam approved these changes

2024-09-28 18:42 UTC, DominMFD approved these changes

2024-09-28 19:13 UTC, merged