Feat: tela de registro
devhatt/octopost pull request #604
Opened 2024-09-02 13:18 UTC by lfelipessilva

Closes #597 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

- tela de registro
- inputs de texto

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
![image](https://github.com/user-attachments/assets/6f67775b-9aeb-47e5-b617-b498047c135a)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

2024-09-02 19:44 UTC, juliaam commented
Tem alguns testes unitários com erro, consegue dar uma olhada nisso?

2024-09-03 12:37 UTC, Alecell requested changes
Iae Felipe, man seu códito ta muito bom e vi que vc seguiu bem os padrões do time e deu um super gás nele!

Só queria saber, como PR é bem grande e tem umas coisas bem grandes pra gente ajustar, vc tem um tempinho que a gente consiga parear pra passarmos pelo seu PR?

2024-09-03 18:33 UTC, juliaam requested changes
Tive a impressão dos elementos da página estarem um pouco pequenos, dei uma checada com um zoom maior e  com 125% ou 150% que pareceu estar proporcional ao tamanho da home, dá uma olhada

home 100%

![image](https://github.com/user-attachments/assets/a1d97e88-609a-47aa-9c2c-fbd3b61c3fdb)

register 100% 

![image](https://github.com/user-attachments/assets/ea5e74cc-3327-45e1-a28a-25787172841f)

125%

![image](https://github.com/user-attachments/assets/55977216-0b7e-4e20-8339-5a69c3a9d048)


150%

![image](https://github.com/user-attachments/assets/afa41d0c-5183-49f3-9e61-121ad2356a7c)

Dito essas coisas, esse pr está *muito* bem feito, parabéns, você é bom!

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/MobileHero/images/octo.svg
mesma coisa do que eu comentei do desktop

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/register.tsx
> +      <DesktopHero /> {/* only on desktops */}
pode tirar esses comentários

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/register.tsx
> +      <MobileHero /> {/* only on mobiles */}
remove comentário

2024-09-03 18:33 UTC, juliaam commented on src/components/TextInput/TextInput.module.scss
> +@mixin apply-color($color) {
não parece que você utilizou o apply-color, pelo menos eu não entendi
se não tiver usando, pode apagar

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/Footer/Footer.module.scss
Além disso, no mobile, a parte do "Already have an account" nao está ficando embaixo independente do tamanho, então, em telas maiores, fica um pouco esquisito, pq não essa parte do layout não está acompanhando

![image](https://github.com/user-attachments/assets/027ee968-eee9-4aea-a764-317095d7efab)

2024-09-03 18:33 UTC, juliaam commented on src/components/TextInput/TextInput.tsx
> +        {renderRightIcon()}
nosso style guide mudou, agora, não queremos mais essas funções de renderizações para evitar má perfomance no react por muitas rerenders. Crie um arquivo TextInput.components.tsx e coloque essa função lá, aqui você utilizará ele como um componente, como <renderRightIcon />. Tem um exemplo no componente do sidebar nos ternários e também no componente do PreviewModeSelector. Se precisar ou tiver alguma dúvida, chama na thread do discord!

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/Footer/Footer.module.scss
> +  p {
não utilize as tags diretamente, prefira dar class a elas e utilizá-las aqui

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/Footer/Footer.module.scss
> +  a {
tag direta

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/MobileHero/Hero.module.scss
> +  // work around (gambiarra) to slice the logo's bottom and right part
eita caraca, tem que ver com os universitários sobre essa parte! kkkkk @Alecell @diogocaronte

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/SignUpPromotion/SignUpPromotion.module.scss
> +  h2 {
tag direta

2024-09-03 18:33 UTC, juliaam commented on src/pages/register/components/SignUpPromotion/SignUpPromotion.module.scss
> +  h3 {
tag direta

2024-09-03 20:21 UTC, DominMFD requested changes
Cara, vc amassou muito, vc é muito bom

2024-09-03 20:21 UTC, DominMFD commented on src/pages/register/components/MobileHero/Hero.tsx
> +        {/* TODO: check route name */}
Pode remover esse TODO por favor

2024-09-03 20:21 UTC, DominMFD commented on src/pages/register/components/SocialLogin/SocialLogin.tsx
> +  // TODO: handle social logins
Pode tirar esse TODO e cria uma task disso por favor, vc pode abrir uma issue em nosso projeto sem problemas. Estamos parando de usar TODOs.

2024-09-03 20:21 UTC, DominMFD commented on src/pages/register/components/Footer/Footer.tsx
Esse componente não é Footer, da para pensar numa nomenclatura melhor pra ele.

2024-09-04 18:14 UTC, Luiginicoletti approved these changes
Looks good

2024-09-05 12:16 UTC, Alecell requested changes
O componente `TextInput` tem alguns problemas fortes que vamos precisar ajustar, mas não precisamos ajustar isso nesse PR! O componente é extremamente complicado de fazer e por hora esse ta atendendo a necessidade então ta perfeito! Se quiser podemos falar sobre depois

2024-09-05 12:16 UTC, Alecell commented on src/pages/register/components/DesktopHero/Hero.tsx
> +        </button>
Usar o componente button que já temos, me chama se precisar, acredito que ele é complicadinho de usar mesmo

2024-09-05 12:16 UTC, Alecell commented on src/pages/register/components/SocialLogin/SocialLogin.tsx
> +        </button>
Usar o componente de button tbm, ele tem versões icon e rounded

2024-09-05 12:16 UTC, Alecell commented on src/pages/register/register.module.scss
> +    max-width: min(460px, calc(100% - 1.25rem));
Precisamos do `calc`? Não pode ser tipo 90% ou coisa assim?

2024-09-05 12:16 UTC, Alecell commented on src/pages/register/components/MobileHero/Hero.tsx
> +          details and start your journey with us
remove o `br`, faz o container ter um tamanho máximo em % que satisfaça a resolução do layout

2024-09-05 12:16 UTC, Alecell commented on src/pages/register/components/MobileHero/Hero.tsx
> +        </button>
Usar o componente button

2024-09-05 12:16 UTC, Alecell commented on src/pages/register/components/MobileHero/Hero.module.scss
`letter-spacing` a mesma coisa do que comentei lá, alias, isso vale pra todos os arquivos!

2024-09-05 14:43 UTC, lfelipessilva commented on src/pages/register/components/DesktopHero/Hero.module.scss
> +  z-index: 1;
Nesse caso o ícone do octopost que fica cortado no meio está na verdade atrás desse componente aí. a regra é simplesmente que ele fique no meio da tela. por isso eu uso esse z-index. Talvez daria pra usar outra regra no ícone, e aí evitaria de ter o overlap das divs

2024-09-05 14:44 UTC, lfelipessilva commented on src/pages/register/components/DesktopHero/Hero.module.scss
Eu removi nos lugares que achei desnecessário, mas em alguns títulos e descrições importantes eu subtituí por rem

2024-09-05 14:45 UTC, lfelipessilva commented on src/pages/register/register.module.scss
> +    max-width: min(460px, calc(100% - 1.25rem));
é pq o padding do design está em 20px, e pra seguir essa regra de sempre manter 20px em dispositívos móveis eu usei o calc. 
*esse valor aí está errado, era pra ser 2rem ao invés de 1.25, eu ajustei também

2024-09-05 18:14 UTC, juliaam requested changes
acabei não vendo no primeiro review, mas essa parte de "Or sign up with" está um pouco diferente. No seu PR tá faltando o divider e o texto está um pouco diferente, consegue arrumar? 

![image](https://github.com/user-attachments/assets/f0248471-ce1e-48a8-8815-685f4a67fd34)

![image](https://github.com/user-attachments/assets/e283106c-b8e1-47b9-a3d5-3b1f657ccc51)

2024-09-05 18:14 UTC, juliaam commented on src/pages/register/components/Form/images/octo.svg
Você tá usando o msm svg em dois locais, está usando aqui também src/pages/register/components/MobileHero/images/octo.svg

Crie um images no register e coloque esse svg lá, aí você importa nos dois locais desse images, sem repetição de svg no projeto

2024-09-05 18:14 UTC, juliaam commented on src/pages/register/components/MobileHero/Hero.module.scss
> +}
conseguiu ver essa situação?

2024-09-05 18:17 UTC, juliaam commented
e atualiza a branch! 😄

2024-09-06 01:03 UTC, lfelipessilva commented on src/pages/register/components/Form/images/octo.svg
essa [pergunta](https://stackoverflow.com/a/76389801/16593271) do stack overflow explica pq eu fiz assim, eu mesmo descobri enquanto desenvolvia que

2024-09-06 01:06 UTC, lfelipessilva commented on src/pages/register/components/Form/images/octo.svg
a gente pode discutir outras soluções se você ou mais alguém pensar em algo, mas a melhor solução pro caso eu acho que foi repetir os svgs

2024-09-06 17:03 UTC, juliaam approved these changes

2024-09-06 20:49 UTC, Alecell requested changes

2024-09-06 20:49 UTC, Alecell commented on src/pages/register/register.module.scss
> +@include from905 {
Opa, media query duplicada!

2024-09-09 00:07 UTC, Alecell approved these changes

2024-09-09 00:08 UTC, merged