fix: collapse main composer
devhatt/octopost pull request #615
Opened 2024-09-07 00:05 UTC by joaomarcelo09

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  When the main composer collapse, the text is lost.

- **Cause**
   The validation was if props.is Open is true it returns the content but if it does not return null, so the component was not being hidden, it was being unmounted.

- **Solution**
  I change the validation to if the props.isOpen is true send "expanded" variant to prop animate in motion and if is false send "collapsed"
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-09-07 10:27 UTC, JpBurgarelli requested changes
Opa, João, tudo bem? Seu PR tem algumas falhas que você precisa verificar nos arquivos de teste `Accordion.spec.tsx`, `sideBar.spec.tsx`, e `SocialAccordion.spec.tsx`. Dentro da sua branch, antes de commitar as coisas, rode um pnpm test.

No template do PR, você precisa linkar o seu PR com a task que você pegou. Por exemplo, se o ID da task que você pegou é 642, logo após o 'close', coloque close #642. Por padrão, a descrição do PR aqui  é em português, apesar de o código ter que ser em inglês.

2024-09-09 11:12 UTC, DominMFD reviewed
Arruma os testes e atualiza a branch

2024-09-09 14:51 UTC, Luiginicoletti commented
Bom dia meu mano, ajusta o CI/CD pra gente dar continuidade ao review, qualquer duvida chama nois.

![salonline-youtuber-curly-tamo-tgzsvyb4ezq7b1bwih](https://github.com/user-attachments/assets/7dea757f-8f9f-4373-859a-22835589672f)

2024-10-03 16:34 UTC, DominMFD approved these changes

2024-10-03 20:14 UTC, juliaam requested changes

2024-10-03 20:14 UTC, juliaam commented on src/components/Accordion/Accordion.tsx
> +      opacity: 1,
precisa do opacity?

2024-10-03 20:14 UTC, juliaam commented on src/components/Accordion/Accordion.tsx
> +    collapsed: { height: 0, opacity: 0 },
precisa do opacity?

2024-10-03 20:14 UTC, juliaam commented on src/components/Accordion/Accordion.tsx
> +          variants={computeVariants()}
nao dava pro computeVariants() ser uma variável?

2024-10-04 00:01 UTC, juliaam commented
ajusta os conflitos

2025-05-21 01:58 UTC, closed without merging